# Generated by Django 5.2.17 on 2026-09-24 12:13

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0018_price_markups_189'),
        ('sales', '0007_alter_sale_options_salecditem_unit_cost_snapshot_and_more'),
        ('warehouse', '0004_alter_warehouse_options_warehousestoragelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBudget',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.PositiveBigIntegerField(unique=True)),
                ('schema', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Яндекс Маркет FBS', max_length=200, verbose_name='Название')),
                ('business_id', models.PositiveBigIntegerField(unique=True, verbose_name='businessId')),
                ('campaign_id', models.PositiveBigIntegerField(unique=True, verbose_name='campaignId')),
                ('partner_warehouse_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Склад Маркета')),
                ('stock_api', models.CharField(choices=[('partner', 'Склад кабинета (v3)'), ('group', 'Группа складов (v2)')], default='partner', max_length=20, verbose_name='API остатков')),
                ('price_scope', models.CharField(choices=[('business', 'Весь кабинет'), ('campaign', 'Этот магазин')], default='business', max_length=20, verbose_name='Область цены')),
                ('enabled', models.BooleanField(default=False, verbose_name='Фоновый обмен включён')),
                ('import_orders_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало импорта заказов')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('configuration', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfillment_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Склад выполнения заказов')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за автоматические операции')),
            ],
            options={
                'permissions': [('manage_settings', 'Яндекс Маркет: настройки'), ('edit_content', 'Яндекс Маркет: контент товаров'), ('bind_offer', 'Яндекс Маркет: привязка товаров'), ('rebind_offer', 'Яндекс Маркет: перепривязка и отвязка'), ('retry_sync', 'Яндекс Маркет: синхронизация'), ('manage_orders', 'Яндекс Маркет: обработка заказов'), ('print_labels', 'Яндекс Маркет: печать ярлыков'), ('accept_return', 'Яндекс Маркет: приём возврата')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yandex_market.integration')),
            ],
        ),
        migrations.CreateModel(
            name='OfferConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('managed', models.BooleanField(default=False, verbose_name='Управление подтверждено')),
                ('sell_on_yandex', models.BooleanField(default=False, verbose_name='Продаётся на Яндекс Маркете')),
                ('is_new', models.BooleanField(default=False)),
                ('content', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('dirty_fields', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('delete_fields', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('parameters', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('category_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('linked', 'Ожидает включения управления'), ('queued', 'В очереди'), ('syncing', 'Синхронизация'), ('synced', 'Синхронизирован'), ('error', 'Ошибка'), ('attention', 'Требуется внимание')], default='linked', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_sent_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yandex_connections', to='catalog.cd')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='yandex_market.integration')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yandex_connections', to='catalog.tech')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='yandex/products/%Y/%m/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='yandex_market.offerconnection')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(blank=True, max_length=64)),
                ('substatus', models.CharField(blank=True, max_length=100)),
                ('created_remote_at', models.DateTimeField(blank=True, null=True)),
                ('updated_remote_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('delivery', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('items', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('prices', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('boxes', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('fake', models.BooleanField(default=False)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('shipped_once', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='yandex_market.integration')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yandex_order', to='sales.sale')),
            ],
            options={
                'ordering': ['-order_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_item_id', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='yandex_market.offerconnection')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='yandex_market.ordermetadata')),
            ],
        ),
        migrations.CreateModel(
            name='LabelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ids', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('report_id', models.CharField(blank=True, max_length=100)),
                ('shipment_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('box_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('format', models.CharField(default='A7', max_length=50)),
                ('state', models.CharField(default='pending', max_length=30)),
                ('file', models.FileField(blank=True, upload_to='yandex/labels/%Y/%m/')),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yandex_market.integration')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labels', to='yandex_market.ordermetadata')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('market_sku', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=512)),
                ('card_status', models.CharField(blank=True, max_length=80)),
                ('content_rating', models.IntegerField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('card', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('remote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remote_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_checked_at', models.DateTimeField(blank=True, null=True)),
                ('price_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='yandex_market.integration')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='offerconnection',
            name='remote_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='yandex_market.remoteoffer'),
        ),
        migrations.CreateModel(
            name='ReturnMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(blank=True, max_length=100)),
                ('snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='yandex_market.ordermetadata')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(max_length=30)),
                ('payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('state', models.CharField(db_index=True, default='pending', max_length=20)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('claimed_generation', models.PositiveIntegerField(default=0)),
                ('lease', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='yandex_market.integration')),
            ],
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=100)),
                ('direction', models.CharField(default='out', max_length=10)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('http_status', models.PositiveIntegerField(null=True)),
                ('result', models.CharField(max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=200)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='yandex_market.integration')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='yandex_market.syncjob')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=100)),
                ('order_id', models.PositiveBigIntegerField(null=True)),
                ('return_id', models.PositiveBigIntegerField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yandex_market.integration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordermetadata',
            constraint=models.UniqueConstraint(fields=('integration', 'order_id'), name='ym_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'remote_item_id'), name='ym_unique_order_item'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__lte', models.F('quantity'))), name='ym_return_not_above_sold'),
        ),
        migrations.AddConstraint(
            model_name='remoteoffer',
            constraint=models.UniqueConstraint(fields=('integration', 'offer_id'), name='ym_unique_remote_offer'),
        ),
        migrations.AddConstraint(
            model_name='offerconnection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('tech__isnull', False)), _connector='OR'), name='ym_exactly_one_product'),
        ),
        migrations.AddConstraint(
            model_name='offerconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('remote_offer',), name='ym_one_active_offer'),
        ),
        migrations.AddConstraint(
            model_name='offerconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('cd__isnull', False)), fields=('integration', 'cd'), name='ym_one_active_cd'),
        ),
        migrations.AddConstraint(
            model_name='offerconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('tech__isnull', False)), fields=('integration', 'tech'), name='ym_one_active_tech'),
        ),
        migrations.AddConstraint(
            model_name='returnmetadata',
            constraint=models.UniqueConstraint(fields=('order', 'return_id'), name='ym_unique_return'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('integration', 'key'), name='ym_unique_event'),
        ),
    ]
