# Generated by Django 5.2.17 on 2026-09-24 12:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconnection',
            name='last_sent_state',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
