# Generated by Django 5.2.17 on 2026-10-09 15:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_market', '0002_offerconnection_last_sent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryschema',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Категория Яндекс Маркета'),
        ),
        migrations.AddField(
            model_name='categoryschema',
            name='placement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Тариф размещения, %'),
        ),
    ]
