# Generated by Django 5.2.17 on 2026-09-08 15:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_alter_cd_barcode_alter_tech_barcode'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ReSOURCE', max_length=255, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('phone_1', models.CharField(blank=True, max_length=40, verbose_name='Телефон №1')),
                ('phone_2', models.CharField(blank=True, max_length=40, verbose_name='Телефон №2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('logo', models.ImageField(blank=True, upload_to='price_documents/', verbose_name='Логотип')),
                ('additional_text', models.TextField(blank=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'настройки документов прайса',
                'verbose_name_plural': 'настройки документов прайса',
                'permissions': [('view_price_page', 'Прайс: просмотр раздела'), ('change_document_settings', 'Прайс: изменение данных документов'), ('generate_retail_price', 'Прайс: создание розничного файла'), ('generate_wholesale_price', 'Прайс: создание оптового файла'), ('download_supplier_template', 'Прайс: скачивание шаблона поставщика'), ('upload_supplier_price', 'Прайс: загрузка цен поставщика'), ('view_supplier_prices', 'Прайс: просмотр цен поставщиков'), ('create_procurement_price_list', 'Прайс: создание закупочного прайса'), ('change_procurement_markup', 'Прайс: изменение наценки'), ('change_procurement_delivery', 'Прайс: изменение доставки'), ('export_procurement_price_list', 'Прайс: экспорт закупочного прайса')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный токен')),
                ('exchange_rate_aed_rub', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Курс AED → RUB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_price_lists', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'закупочный прайс',
                'verbose_name_plural': 'закупочные прайсы',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProcurementPriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название товара')),
                ('article_snapshot', models.CharField(editable=False, max_length=100, verbose_name='Артикул')),
                ('supplier_price_aed', models.DecimalField(decimal_places=6, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Цена поставщика, AED')),
                ('exchange_rate_aed_rub', models.DecimalField(decimal_places=6, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Курс AED → RUB')),
                ('base_price_rub', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='База, RUB')),
                ('markup_rub', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка, RUB')),
                ('delivery_rub', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доставка, RUB')),
                ('prepayment_price_rub', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Цена предоплаты, RUB')),
                ('postpayment_price_rub', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Цена постоплаты, RUB')),
                ('cd', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_price_items', to='catalog.cd', verbose_name='CD')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='price.procurementpricelist', verbose_name='Прайс')),
                ('selected_supplier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='selected_procurement_items', to='partners.supplier', verbose_name='Выбранный поставщик')),
                ('tech', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_price_items', to='catalog.tech', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'позиция закупочного прайса',
                'verbose_name_plural': 'позиции закупочного прайса',
                'ordering': ('product_name_snapshot', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='procurement_price_item_exact_product'), models.UniqueConstraint(condition=models.Q(('cd__isnull', False)), fields=('price_list', 'cd'), name='unique_procurement_price_cd'), models.UniqueConstraint(condition=models.Q(('tech__isnull', False)), fields=('price_list', 'tech'), name='unique_procurement_price_tech'), models.CheckConstraint(condition=models.Q(('base_price_rub__gte', 0)), name='proc_base_nonnegative'), models.CheckConstraint(condition=models.Q(('markup_rub__gte', 0)), name='proc_markup_nonnegative'), models.CheckConstraint(condition=models.Q(('delivery_rub__gte', 0)), name='proc_delivery_nonnegative'), models.CheckConstraint(condition=models.Q(('prepayment_price_rub__gte', 0)), name='proc_prepayment_nonnegative'), models.CheckConstraint(condition=models.Q(('postpayment_price_rub__gte', 0)), name='proc_postpayment_nonnegative')],
            },
        ),
    ]
