# Generated by Django 5.2.17 on 2026-10-06 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementpricelist',
            name='exchange_rate_usdt_aed',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Курс AED → USDT (AED за 1 USDT)'),
        ),
        migrations.AddField(
            model_name='procurementpricelist',
            name='exchange_rate_usdt_rub',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Курс USDT → RUB (RUB за 1 USDT)'),
        ),
    ]
