from django.urls import path
from . import views, retail_views

app_name = "resource_storefront"

urlpatterns = [
    path("crm/integrations/retailer/regenerate/", retail_views.regenerate, name="retail_regenerate"),
    path("opt/", views.home, name="home"),
    path("opt/unavailable/", views.denied, name="denied"),
    path("opt/catalog/", views.catalogue, name="catalogue"),
    path("opt/new/", views.catalogue, {"kind": "new"}, name="new"),
    path("opt/product/<str:kind>/<int:pk>/", views.product_detail, name="product"),
    path("opt/product-photo/<str:kind>/<int:pk>/<int:image_id>/", views.product_photo, name="product_photo"),
    path("opt/content/<str:kind>/<int:pk>/", views.content_asset, name="content_asset"),
    path("opt/news/", views.news_list, name="news_list"),
    path("opt/news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("opt/cart/", views.cart_view, name="cart"),
    path("opt/cart/add/", views.cart_add, name="cart_add"),
    path("opt/cart/update/<str:key>/", views.cart_update, name="cart_update"),
    path("opt/cart/remove/<str:key>/", views.cart_remove, name="cart_remove"),
    path("opt/cart/refresh/", views.cart_refresh, name="cart_refresh"),
    path("opt/checkout/", views.checkout, name="checkout"),
    path("opt/checkout/status/", views.checkout_status, name="checkout_status"),
    path("opt/order/<int:sale_id>/", views.order_success, name="success"),
    path("opt/<str:token>/", views.access, name="access"),
    path("crm/wholesale-contacts/", views.contacts, name="contacts"),
    path("crm/wholesale-contacts/new/", views.contact_save, name="contact_new"),
    path("crm/wholesale-contacts/<int:pk>/edit/", views.contact_save, name="contact_edit"),
    path("crm/wholesale-contacts/<int:pk>/link/", views.link_issue, name="link_issue"),
    path("crm/wholesale-links/<int:pk>/revoke/", views.link_revoke, name="link_revoke"),
    path("crm/integrations/storefront/", views.manage, name="manage"),
    path("crm/integrations/storefront/preview/", views.preview_start, name="preview_start"),
    path("crm/integrations/storefront/settings/", views.settings_save, name="settings_save"),
    path("crm/integrations/storefront/slots/add/", views.slot_add, name="slot_add"),
    path("crm/integrations/storefront/products/<str:kind>/<int:pk>/publication/", views.product_publication, name="product_publication"),
    path("crm/integrations/storefront/slots/<int:pk>/remove/", views.slot_remove, name="slot_remove"),
    path("crm/integrations/storefront/news/new/", views.news_save, name="news_new"),
    path("crm/integrations/storefront/news/<int:pk>/edit/", views.news_save, name="news_edit"),
    path("crm/integrations/storefront/news/<int:pk>/unpublish/", views.news_unpublish, name="news_unpublish"),
    path("crm/integrations/storefront/collections/new/", views.collection_save, name="collection_new"),
    path("crm/integrations/storefront/collections/<int:pk>/edit/", views.collection_save, name="collection_edit"),
    path("crm/integrations/storefront/collections/<int:pk>/items/add/", views.collection_product_add, name="collection_product_add"),
    path("crm/integrations/storefront/collection-items/<int:pk>/remove/", views.collection_product_remove, name="collection_product_remove"),
    path("crm/integrations/storefront/news/<int:pk>/products/add/", views.news_product_add, name="news_product_add"),
    path("crm/integrations/storefront/news-products/<str:kind>/<int:pk>/remove/", views.news_product_remove, name="news_product_remove"),
]
