# Generated by Django 5.2.17 on 2026-09-01 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('USD_RUB', 'USD/RUB'), ('AED_RUB', 'AED/RUB'), ('USD_AED', 'USD/AED')], max_length=7, unique=True, verbose_name='Валютная пара')),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Курс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'курс валют',
                'verbose_name_plural': 'курсы валют',
                'permissions': [('access_admin_panel', 'Может входить в административную панель')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__isnull', True), _connector='OR'), name='currency_rate_nonnegative')],
            },
        ),
    ]
