# Generated by Django 5.2.17 on 2026-09-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_supplier_price_default_zero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercdprice',
            options={'permissions': [('view_pricing', 'Может просматривать ценообразование'), ('view_supplier_prices', 'Может просматривать текущие цены поставщиков'), ('change_supplier_prices', 'Может изменять текущие цены поставщиков'), ('change_retail_price', 'Может изменять цены Avito'), ('change_wholesale_price', 'Может изменять оптовые цены'), ('change_yandex_market_price', 'Может изменять цены Яндекс Маркет')], 'verbose_name': 'текущая цена поставщика на CD', 'verbose_name_plural': 'текущие цены поставщиков на CD'},
        ),
    ]
