# Generated by Django 5.2.17 on 2026-09-01 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('legal_entity', models.CharField(max_length=255, verbose_name='Юридическое лицо')),
                ('phone_1', models.CharField(max_length=40, verbose_name='Телефон №1')),
                ('phone_2', models.CharField(blank=True, max_length=40, verbose_name='Телефон №2')),
                ('phone_3', models.CharField(blank=True, max_length=40, verbose_name='Телефон №3')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'площадка реализации',
                'verbose_name_plural': 'площадки реализации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('letter', models.CharField(max_length=8, unique=True, verbose_name='Буква')),
                ('highlight_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Укажите цвет в формате #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Цвет')),
                ('legal_entity', models.CharField(max_length=255, verbose_name='Юридическое лицо')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_1', models.CharField(max_length=40, verbose_name='Телефон №1')),
                ('phone_2', models.CharField(blank=True, max_length=40, verbose_name='Телефон №2')),
                ('phone_3', models.CharField(blank=True, max_length=40, verbose_name='Телефон №3')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ('letter',),
                'permissions': [('view_supplier_details', 'Может видеть полные данные поставщиков')],
            },
        ),
    ]
