# Generated by Django 5.2.17 on 2026-09-12 16:07

import django.core.validators
from django.db import migrations, models


def assign_supplier_priorities(apps, schema_editor):
    Supplier = apps.get_model("partners", "Supplier")
    for letter, priority in (("A", 1), ("F", 2), ("M", 3)):
        Supplier.objects.filter(letter=letter).update(priority=priority)


def reset_supplier_priorities(apps, schema_editor):
    Supplier = apps.get_model("partners", "Supplier")
    Supplier.objects.filter(letter__in=("A", "F", "M")).update(priority=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='priority',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приоритет'),
        ),
        migrations.RunPython(assign_supplier_priorities, reset_supplier_priorities),
    ]
