# Generated by Django 5.2.17 on 2026-09-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_transfers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('name',), 'permissions': [('view_global_stock', 'Может просматривать общие остатки'), ('view_warehouse_stock', 'Может просматривать остатки отдельного склада'), ('change_storage_location', 'Может изменять места хранения товаров')], 'verbose_name': 'склад', 'verbose_name_plural': 'склады'},
        ),
        migrations.CreateModel(
            name='WarehouseStorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=1, verbose_name='Помещение')),
                ('rack', models.PositiveIntegerField(verbose_name='Стеллаж')),
                ('shelf', models.PositiveIntegerField(verbose_name='Полка')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='Столбцы')),
                ('canonical_value', models.CharField(editable=False, max_length=255, verbose_name='Каноническое значение')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'место хранения на складе',
                'verbose_name_plural': 'места хранения на складах',
                'ordering': ('room', 'rack', 'shelf', 'canonical_value', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TechWarehouseStorageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_assignments', to='warehouse.techwarehousestock', verbose_name='Остаток Tech')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_assignments', to='warehouse.warehousestoragelocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'размещение техники на складе',
                'verbose_name_plural': 'размещения техники на складах',
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CDWarehouseStorageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_assignments', to='warehouse.cdwarehousestock', verbose_name='Остаток CD')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cd_assignments', to='warehouse.warehousestoragelocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'размещение CD на складе',
                'verbose_name_plural': 'размещения CD на складах',
                'ordering': ('position', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='warehousestoragelocation',
            index=models.Index(fields=['warehouse', 'room', 'rack', 'shelf'], name='storage_location_lookup'),
        ),
        migrations.AddConstraint(
            model_name='warehousestoragelocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'canonical_value'), name='unique_storage_location_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehousestoragelocation',
            constraint=models.CheckConstraint(condition=models.Q(('rack__gt', 0)), name='storage_location_rack_positive'),
        ),
        migrations.AddConstraint(
            model_name='warehousestoragelocation',
            constraint=models.CheckConstraint(condition=models.Q(('shelf__gt', 0)), name='storage_location_shelf_positive'),
        ),
        migrations.AddConstraint(
            model_name='techwarehousestorageassignment',
            constraint=models.UniqueConstraint(fields=('stock', 'location'), name='unique_tech_stock_storage_location'),
        ),
        migrations.AddConstraint(
            model_name='techwarehousestorageassignment',
            constraint=models.UniqueConstraint(fields=('stock', 'position'), name='unique_tech_stock_storage_position'),
        ),
        migrations.AddConstraint(
            model_name='cdwarehousestorageassignment',
            constraint=models.UniqueConstraint(fields=('stock', 'location'), name='unique_cd_stock_storage_location'),
        ),
        migrations.AddConstraint(
            model_name='cdwarehousestorageassignment',
            constraint=models.UniqueConstraint(fields=('stock', 'position'), name='unique_cd_stock_storage_position'),
        ),
    ]
