# Generated by Django 5.2.17 on 2026-10-04 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_cd_wholesale_site_enabled_and_more'),
        ('warehouse', '0005_transfer_cost_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_revisions_started', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'ревизия склада',
                'verbose_name_plural': 'ревизии складов',
            },
        ),
        migrations.CreateModel(
            name='WarehouseRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_revision_items', to='catalog.cd')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_revision_checks', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehouserevision')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_revision_items', to='catalog.tech')),
            ],
            options={
                'verbose_name': 'отметка ревизии склада',
                'verbose_name_plural': 'отметки ревизии склада',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouserevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('warehouse',), name='one_active_warehouse_revision'),
        ),
        migrations.AddConstraint(
            model_name='warehouserevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('is_active', True)), models.Q(('closed_at__isnull', False), ('is_active', False)), _connector='OR'), name='warehouse_revision_closed_state'),
        ),
        migrations.AddConstraint(
            model_name='warehouserevisionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('tech__isnull', False)), _connector='OR'), name='revision_item_one_product'),
        ),
        migrations.AddConstraint(
            model_name='warehouserevisionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('cd__isnull', False)), fields=('revision', 'cd'), name='unique_revision_cd'),
        ),
        migrations.AddConstraint(
            model_name='warehouserevisionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('tech__isnull', False)), fields=('revision', 'tech'), name='unique_revision_tech'),
        ),
        migrations.AddConstraint(
            model_name='warehouserevisionitem',
            constraint=models.CheckConstraint(condition=models.Q(('checked', False), ('checked_at__isnull', False), _connector='OR'), name='revision_checked_has_date'),
        ),
    ]
