"""Детерминированная первичная классификация исторического каталога CD.

Не вызывается при обычном создании/редактировании товара. Не обращается к сети.
Незнакомое название сохраняется как самостоятельная серия, а не угадывается
по первому слову. Известные франшизы перечислены явно и в приоритетном порядке.
"""

import re
import unicodedata

from .models import normalize_game_series_name


# Канонические франшизы и проверенные варианты написания в рабочей базе.
# Более узкие серии должны стоять раньше широких (например, Batman: Arkham).
CURATED_VARIANTS = (
    ("Achilles", ("achiles double pack", "achilles double pack", "achilles: legends untold", "achilles: survivor")),
    ("Alien", ("alien isolation", "aliens: dark descent")),
    ("Dakar Desert Rally", ("dakar desert rally",)),
    ("Front Mission", ("front mission",)),
    ("Mana", ("visions of mana", "trials of mana", "legend of mana")),
    ("Sacred", ("fallen angel sacred",)),
    ("Street Fighter", ("ultra street fighter",)),
    ("Styx", ("styx blades of greed", "styx: blades of greed")),
    ("Wo Long: Fallen Dynasty", ("wolong fallen dynasty", "wo long: fallen dynasty")),
    ("Assassin's Creed", ("assasin's creed", "assassin shadows")),
    ("Resident Evil", ("resident evi ",)),
    ("Demon's Souls", ("demon souls",)),
    ("The Legend of Zelda", ("the legends of zelda",)),
    ("Star Wars", ("star war squadrons", "starwar squadrons")),
    ("Sonic the Hedgehog", ("team sonic racing",)),
    ("EA Sports FC", ("fc24",)),
    ("WWE 2K", ("w2k",)),
    ("Madden NFL", ("nfl madden", "nfl 26 madden")),
    ("Like a Dragon / Yakuza", ("yakudza",)),
    ("Judgment", ("judgement", "judgment ", "lost judgment")),
    ("Dragon Quest", ("dragon monsters the dark prince",)),
    ("The Legend of Heroes", ("trails in the sky",)),
    ("Final Fantasy", ("stranger of paradise: final fantasy",)),
    ("LEGO Jurassic World", ("lego jurasic",)),
    ("LEGO Marvel", ("lego super heroes",)),
    ("Fast & Furious", ("fast&furious",)),
    ("Batman: Arkham", ("batman: arkham",)),
    ("Mario & Luigi", ("mario & luigi",)),
    ("Paper Mario", ("paper mario",)),
    ("Mario & Sonic", ("mario & sonic",)),
    ("Super Mario", ("mario galaxy", "mario maker", "mario rabbids")),
    ("Kingdom Come: Deliverance", ("kingdom come deliverance",)),
    ("Evil Nun", ("evil nun",)),
    ("Art of Rally", ("art of rally",)),
    ("Baby Shark: Sing & Swim Party", ("baby shark sing", "baby shark: sing")),
    ("Cris Tales", ("cris tales", "cristales")),
    ("Fate/Samurai Remnant", ("fate samurai", "fate/samurai")),
    ("Firefighting Simulator", ("firefighting simularor", "firefighting simulator")),
    ("Karma: The Dark World", ("karma limited", "karma: the dark world")),
    ("My Little Pony", ("liitle pony", "little pony", "my little pony")),
    ("MOUSE: P.I. For Hire", ("mouse p.i.", "mouse: p.i.")),
    ("On the Road Truck Simulator", ("one the road truck simulator", "on the road truck simulator")),
    ("Rise of the Ronin", ("the rise of ronnin", "rise of the ronin")),
    ("Shotgun King", ("shot gun king", "shotgun king")),
    ("Theatrhythm Final Bar Line", ("theatrhythim final bar line", "theatrhythm final bar line")),
    ("Tiebreak", ("tiebreak",)),
    ("Truck & Logistics Simulator", ("truck & logistics",)),
    ("UFO Robot Grendizer", ("ufo robot grendizer",)),
    ("30 in 1 Game Collection", ("30 in 1 game collection",)),
    ("The Nightmare Box", ("the nightmare box",)),
    ("63 Days", ("63 days",)),
    ("After the Fall", ("after the fall",)),
    ("Alaskan Road Truckers", ("alaskan road truckers",)),
    ("Aphelion", ("aphelion:",)),
    ("Asphalt Legends Unite", ("asphalt legends unite",)),
    ("Dragon Is Dead", ("dragon is dead",)),
    ("Gloomhaven", ("gloomhaven",)),
    ("Humankind", ("humankind",)),
    ("Insomnis", ("insomnis",)),
    ("Kong: Survivor Instinct", ("kong: survivor instinct",)),
    ("Lil Gator", ("lil gator",)),
    ("LISA", ("lisa defenitive", "lisa ")),
    ("Murky Divers", ("murky divers",)),
    ("Rooftops & Alleys", ("rooftops & alleys",)),
    ("Shredders", ("shredders",)),
    ("The Inquisitor", ("the inquisitor",)),
    ("War Mongrels", ("war mongrels",)),
    ("World Championships NES", ("world championships nes",)),
)

FRANCHISE_ALIASES = (
    ("Batman: Arkham", ("batman arkham", "batman: arkham", "batman return to arkham")),
    ("LEGO Batman", ("lego batman",)),
    ("LEGO Marvel", ("lego marvel",)),
    ("LEGO Star Wars", ("lego star wars",)),
    ("LEGO Harry Potter", ("lego harry potter",)),
    ("LEGO Jurassic World", ("lego jurassic",)),
    ("LEGO The Movie", ("lego movie", "the lego movie")),
    ("Marvel's Spider-Man", ("marvel's spider-man", "marvel spider-man", "spider man", "spider-man")),
    ("Marvel Cosmic Invasion", ("marvel cosmic invasion",)),
    ("Marvel's Avengers", ("marvel's avengers", "marvel avengers")),
    ("Star Wars Jedi", ("star wars jedi",)),
    ("Star Wars", ("star wars",)),
    ("The Legend of Zelda", ("the legend of zelda", "zelda ", "hyrule warriors")),
    ("Super Mario", ("super mario", "new super mario", "mario bros", "mario kart", "mario party", "mario tennis", "mario golf", "mario strikers", "mario + rabbids", "mario & rabbids", "mario vs")),
    ("Donkey Kong", ("donkey kong",)),
    ("Kirby", ("kirby ",)),
    ("Pokémon", ("pokemon ", "pokémon ", "detective pikachu")),
    ("Sonic the Hedgehog", ("sonic ", "sonic:", "shadow generations")),
    ("Crash Bandicoot", ("crash bandicoot", "crash team")),
    ("Spyro", ("spyro ",)),
    ("Assassin's Creed", ("assassin's creed", "assassins creed", "assasins creed", "assassin creed", "assassins �reed")),
    ("Resident Evil", ("resident evil", "resedint evil")),
    ("The Last of Us", ("the last of us",)),
    ("Call of Duty", ("call of duty", "cod ",)),
    ("Battlefield", ("battlefield ",)),
    ("Far Cry", ("far cry",)),
    ("Watch Dogs", ("watch dog",)),
    ("Tom Clancy's Ghost Recon", ("tom clancy's ghost recon", "tom clancy�s ghost recon", "ghost recon")),
    ("Tom Clancy's Rainbow Six", ("tom clancy's rainbow six", "rainbow six")),
    ("Tom Clancy's The Division", ("tom clancy's the division", "the division ",)),
    ("Grand Theft Auto", ("gta ", "grand theft auto")),
    ("Red Dead Redemption", ("red dead redemption",)),
    ("Saints Row", ("saints row",)),
    ("Mafia", ("mafia ", "mafia:")),
    ("Hitman", ("hitman ",)),
    ("Metal Gear", ("metal gear",)),
    ("Death Stranding", ("death stranding",)),
    ("God of War", ("god of war",)),
    ("Horizon", ("horizon zero dawn", "horizon forbidden west", "horizon call of the mountain", "horizon adventures")),
    ("Ghost of Tsushima", ("ghost of tsushima",)),
    ("Ghost of Yōtei", ("ghost of yotei", "ghost of yōtei")),
    ("Uncharted", ("uncharted ",)),
    ("Tomb Raider", ("tomb raider", "rise of the tomb raider", "shadow of the tomb raider")),
    ("The Elder Scrolls", ("the elder scrolls", "elder scrolls", "skyrim ", "skyrim:")),
    ("Fallout", ("fallout ",)),
    ("The Witcher", ("the witcher", "witcher ", "gwent ",)),
    ("Cyberpunk 2077", ("cyberpunk",)),
    ("Elden Ring", ("elden ring",)),
    ("Dark Souls", ("dark souls",)),
    ("Demon's Souls", ("demon's souls", "demons souls")),
    ("Bloodborne", ("bloodborne",)),
    ("Armored Core", ("armored core",)),
    ("Sekiro", ("sekiro",)),
    ("Final Fantasy", ("final fantasy", "finalfantasy")),
    ("Dragon Quest", ("dragon quest",)),
    ("Dragon Ball", ("dragon ball",)),
    ("Monster Hunter", ("monster hunter",)),
    ("Persona", ("persona ",)),
    ("Like a Dragon / Yakuza", ("like a dragon", "yakuza ")),
    ("Ninja Gaiden", ("ninja gaiden",)),
    ("Onimusha", ("onimusha",)),
    ("Devil May Cry", ("devil may cry",)),
    ("Bayonetta", ("bayonetta ",)),
    ("Kingdom Hearts", ("kingdom hearts",)),
    ("Tales of", ("tales of ",)),
    ("Octopath Traveler", ("octopath traveler",)),
    ("Fire Emblem", ("fire emblem",)),
    ("Metroid", ("metroid ",)),
    ("Xenoblade Chronicles", ("xenoblade",)),
    ("Bravely Default", ("bravely default",)),
    ("Digimon", ("digimon ",)),
    ("One Piece", ("one piece",)),
    ("Naruto", ("naruto ",)),
    ("Demon Slayer", ("demon slayer",)),
    ("Atelier", ("atelier ",)),
    ("Ys", ("ys ",)),
    ("Disgaea", ("disgaea ",)),
    ("The Legend of Heroes", ("the legend of heroes", "trails of ", "trails through ")),
    ("NieR", ("nier ", "nier:")),
    ("Mortal Kombat", ("mortal kombat",)),
    ("Street Fighter", ("street fighter",)),
    ("Tekken", ("tekken ",)),
    ("Dead or Alive", ("dead or alive",)),
    ("Injustice", ("injustice ",)),
    ("Civilization", ("civilization ", "sid meier's civilization")),
    ("Anno", ("anno ",)),
    ("Minecraft", ("minecraft",)),
    ("ARK", ("ark:", "ark ", "ark survival")),
    ("Diablo", ("diablo ",)),
    ("Borderlands", ("borderlands ", "tiny tina's wonderlands")),
    ("BioShock", ("bioshock",)),
    ("Dying Light", ("dying light",)),
    ("Dead Island", ("dead island",)),
    ("Dead Rising", ("dead rising",)),
    ("The Evil Within", ("the evil within",)),
    ("Silent Hill", ("silent hill",)),
    ("Five Nights at Freddy's", ("five nights at freddy", "five nights at freddys")),
    ("Little Nightmares", ("little nightmares",)),
    ("Hello Neighbor", ("hello neighbor",)),
    ("The Dark Pictures Anthology", ("the dark pictures", "dark pictures")),
    ("A Plague Tale", ("a plague tale",)),
    ("Bendy", ("bendy ",)),
    ("Blasphemous", ("blasphemous",)),
    ("Tormented Souls", ("tormented souls",)),
    ("FATAL FRAME", ("fatal frame", "project zero")),
    ("Alan Wake", ("alan wake",)),
    ("Control", ("control ",)),
    ("Sniper Elite", ("sniper elite",)),
    ("Sniper: Ghost Warrior", ("sniper: ghost warrior", "sniper ghost warrior")),
    ("Just Cause", ("just cause",)),
    ("Need for Speed", ("need for speed", "nfs ",)),
    ("Forza Horizon", ("forza horizon",)),
    ("Forza Motorsport", ("forza motorsport",)),
    ("Gran Turismo", ("gran turismo",)),
    ("The Crew", ("the crew ",)),
    ("Hot Wheels", ("hot wheels",)),
    ("EA Sports FC", ("ea sports fc", "ea fc ", "fc ", "fc25", "fc26", "fifa ", "ea fifa")),
    ("NBA 2K", ("nba 2k",)),
    ("WWE 2K", ("wwe 2k",)),
    ("Madden NFL", ("madden nfl",)),
    ("MotoGP", ("motogp",)),
    ("F1", ("f1 ", "formula 1 ", "f1:")),
    ("PAW Patrol", ("paw patrol",)),
    ("Teenage Mutant Ninja Turtles", ("teenage mutant ninja", "tmnt ", "ninja turtles")),
    ("SpongeBob SquarePants", ("spongebob", "sponge bob", "the patrick star")),
    ("Asterix & Obelix", ("asterix",)),
    ("Agatha Christie", ("agatha christie",)),
    ("Barbie", ("barbie ", "barbie:")),
    ("Cars", ("cars ", "disney pixar cars")),
    ("Jumanji", ("jumanji",)),
    ("Looney Tunes", ("looney tunes",)),
    ("Ben 10", ("ben 10", "ben10")),
    ("My Little Pony", ("my little pony",)),
    ("Peppa Pig", ("peppa pig",)),
    ("Bluey", ("bluey ",)),
    ("Avatar: The Last Airbender", ("avatar the last airbender", "avatar: the last airbender")),
    ("Avatar: Frontiers of Pandora", ("avatar frontiers of pandora", "avatar: frontiers of pandora")),
    ("Jurassic World", ("jurassic world",)),
    ("Fast & Furious", ("fast & furious", "fast and furious")),
    ("Chicken Run", ("chicken run",)),
    ("Captain Tsubasa", ("captain tsubasa",)),
    ("Sword Art Online", ("sword art online", "echoes of aincrad")),
    ("Gears of War", ("gears of war", "gears ",)),
    ("Halo", ("halo ",)),
    ("Fable", ("fable ",)),
    ("Gothic", ("gothic ",)),
    ("Darksiders", ("darksiders", "darsiders")),
    ("Prince of Persia", ("prince of persia",)),
    ("Burnout", ("burnout ",)),
    ("Gear.Club Unlimited", ("gear club", "gear.club")),
    ("Goat Simulator", ("goat simulator",)),
    ("Slay the Spire", ("slay the spire",)),
    ("The Sims", ("the sims", "sims ",)),
    ("PowerWash Simulator", ("powerwash simulator",)),
    ("Life is Strange", ("life is strange",)),
    ("A Quiet Place", ("a quiet place",)),
    ("Monster Jam", ("monster jam",)),
    ("Matchbox Driving Adventures", ("matchbox driving",)),
    ("Destroy All Humans!", ("destroy all humans",)),
    ("Double Dragon", ("double dragon",)),
    ("Contra", ("contra ",)),
    ("Pac-Man", ("pac-man", "pac man")),
    ("Astro Bot", ("astro bot",)),
    ("Sackboy", ("sackboy", "littlebigplanet", "little big planet")),
    ("Ratchet & Clank", ("ratchet",)),
    ("Jak and Daxter", ("jak and daxter",)),
    ("Shin Megami Tensei", ("shin megami tensei",)),
    ("Rune Factory", ("rune factory",)),
    ("Story of Seasons", ("story of seasons",)),
    ("Harvest Moon", ("harvest moon",)),
    ("Dragon's Dogma", ("dragon's dogma", "dragons dogma")),
    ("Nioh", ("nioh ",)),
    ("Monster Rancher", ("monster rancher",)),
    ("Ace Combat", ("ace combat",)),
    ("Animal Crossing", ("animal crossing",)),
    ("Among Us", ("among us",)),
    ("Amerzone", ("amerzone",)),
    ("Assetto Corsa", ("assetto corsa", "asseto corsa")),
    ("Atari", ("atari 50", "atari flashback")),
    ("Axiom Verge", ("axiom verge",)),
    ("Baldur's Gate", ("baldur's gate",)),
    ("Banishers: Ghosts of New Eden", ("banishers",)),
    ("Beyond the Ice Palace", ("beyond the ice palace",)),
    ("BlazBlue", ("blaz blue", "blazblue")),
    ("Callisto Protocol", ("callisto protocol", "the callisto protocol")),
    ("Capcom Fighting Collection", ("capcom fighting collection",)),
    ("Cat Quest", ("cat quest",)),
    ("Clair Obscur: Expedition 33", ("clair obscur expedition", "clair obscur expeditions")),
    ("Code Vein", ("code vein",)),
    ("Coffee Talk", ("coffee talk",)),
    ("Commandos", ("commandos",)),
    ("Company of Heroes", ("company of heroes",)),
    ("Crysis", ("crysis",)),
    ("Cronos: The New Dawn", ("cronos",)),
    ("Darkest Dungeon", ("darkest dungeon",)),
    ("Daymare", ("daymare",)),
    ("Days Gone", ("days gone",)),
    ("Dead Cells", ("dead cells",)),
    ("Dead Space", ("dead space",)),
    ("DOOM", ("doom ",)),
    ("Dragon Age", ("dragon age",)),
    ("Dragon Ball", ("dragonball",)),
    ("Elden Ring", ("elden rng",)),
    ("ELEX", ("elex ",)),
    ("Epic Mickey", ("disney epic mickey", "epic mickey")),
    ("Expeditions: A MudRunner Game", ("expeditions a mudrunner", "expeditions: a mudrunner")),
    ("Fairy Tail", ("fairy tail",)),
    ("Farming Simulator", ("farming simulator", "farmimg simulator")),
    ("Fate/Samurai Remnant", ("fate samurai", "fate/samurai", "samurai kem")),
    ("Fatal Fury", ("fatal fury",)),
    ("Five Nights at Freddy's", ("five nights freddy",)),
    ("Football Manager", ("football manager",)),
    ("Formula Retro Racing", ("formula retro racing",)),
    ("Frostpunk", ("frostpunk",)),
    ("Garfield", ("garfield ",)),
    ("Ghostbusters", ("ghostbusters", "ghostbuster")),
    ("Ghostrunner", ("ghostrunner",)),
    ("Granblue Fantasy", ("granblue fantasy",)),
    ("GRID", ("grid legends", "grid:")),
    ("Hades", ("hades ", "hades ii")),
    ("Hammerwatch", ("hammer watch", "hammerwatch")),
    ("Hell Let Loose", ("hell let loose",)),
    ("Helldivers", ("helldivers",)),
    ("Hogwarts Legacy", ("hogwarts legacy",)),
    ("Hollow Knight", ("hollow knight",)),
    ("Horizon", ("horizon forbidden",)),
    ("Horror Tales", ("horror tales",)),
    ("The House of the Dead", ("house of the dead", "the house of the dead")),
    ("Human: Fall Flat", ("human fall flat", "human: fall flat")),
    ("Ice Age", ("ice age",)),
    ("Immortals Fenyx Rising", ("immortals fenyx rising", "imortals fenyx rising")),
    ("inFAMOUS", ("infamous",)),
    ("Instant Sports", ("instant sports",)),
    ("Just Dance", ("just dance",)),
    ("JoJo's Bizarre Adventure", ("jojo bizarre", "jojo's bizarre")),
    ("Kena: Bridge of Spirits", ("kena",)),
    ("Kingdom Come: Deliverance", ("kingdom come",)),
    ("King's Bounty", ("king's bounty", "kings bounty")),
    ("LEGO City", ("lego city",)),
    ("LEGO DC Super-Villains", ("lego dc",)),
    ("LEGO Ninjago", ("lego ninja",)),
    ("LEGO The Incredibles", ("lego incredibles", "lego the incredibles")),
    ("LEGO Horizon Adventures", ("lego horizon",)),
    ("Legacy of Kain", ("legacy of kain", "soul reaver")),
    ("LittleBig Adventure", ("little big adventure", "littlebig adventure")),
    ("Luigi's Mansion", ("luigi mansion", "luigi's mansion")),
    ("Lumo", ("lumo ",)),
    ("Maneater", ("man eater", "maneater")),
    ("Marvel vs. Capcom", ("marvel vs capcom", "marvel vs. capcom")),
    ("Metro", ("metro exodus", "metro redux", "metro 2033", "metro last light")),
    ("Miraculous", ("miraculous",)),
    ("Mortal Kombat", ("mortal combat",)),
    ("Mortal Shell", ("mortal shell",)),
    ("Mount & Blade", ("mount and blade", "mount blade")),
    ("MudRunner", ("mudrunner",)),
    ("MX vs. ATV", ("mx vs atv",)),
    ("NHL", ("nhl ",)),
    ("Ni no Kuni", ("nino kuni", "ni no kuni")),
    ("No Man's Sky", ("no mans sky", "no man's sky")),
    ("Operation Wolf", ("operation wolf",)),
    ("Overcooked", ("overcooked",)),
    ("Overwatch", ("overwatch",)),
    ("Patapon", ("patapon",)),
    ("PES", ("pes ",)),
    ("Pikmin", ("pikmin",)),
    ("Planet Coaster", ("planet coaster",)),
    ("Plants vs. Zombies", ("plants vs zombies", "plants vs. zombies")),
    ("Poppy Playtime", ("poppy playtime",)),
    ("Power Rangers", ("power rangers",)),
    ("PowerWash Simulator", ("power wash simulator",)),
    ("Predator: Hunting Grounds", ("predator hunting grounds", "predator: hunting grounds")),
    ("Rabbids", ("rabbids",)),
    ("Rayman", ("rayman",)),
    ("Remnant", ("remnant ", "remnant:")),
    ("RoboCop", ("robocop",)),
    ("RollerCoaster Tycoon", ("rollercoaster tycoon",)),
    ("Sacred", ("sacred ",)),
    ("Sea of Stars", ("sea of stars", "sea stars")),
    ("Shadow of Mordor", ("shadow of mordor", "shadow of war")),
    ("Shadow Warrior", ("shadow warrior",)),
    ("SHINOBI", ("shinobi",)),
    ("Slay the Princess", ("slay the princess", "slay the princess")),
    ("Slime Rancher", ("slime rancher",)),
    ("The Smurfs", ("smurf", "the smurfs")),
    ("SnowRunner", ("snowrunner",)),
    ("Soul Hackers", ("soul hackers", "souls hackers")),
    ("South Park", ("south park",)),
    ("Spirit of the North", ("spirit of the north",)),
    ("Splatoon", ("splatoon",)),
    ("Star Fox", ("star fox", "starfox")),
    ("Star Trek", ("star trek",)),
    ("Streets of Rage", ("streets of rage",)),
    ("Subnautica", ("subnautica",)),
    ("Super Bomberman", ("super bomberman",)),
    ("Super Monkey Ball", ("super monkey ball",)),
    ("Syberia", ("syberia",)),
    ("Terminator", ("terminator",)),
    ("Tennis World Tour", ("tennis world tour",)),
    ("Tetris", ("tetris",)),
    ("The Blood of Dawnwalker", ("the blood of dawnwalker",)),
    ("The Last Faith", ("the last faith", "last faith")),
    ("The Outer Worlds", ("the outer worlds",)),
    ("The Walking Dead", ("the walking dead", "walking dead")),
    ("The Yakuza Collection", ("the yakuza collection",)),
    ("Tintin", ("tintin",)),
    ("Tony Hawk's Pro Skater", ("tony hawk", "tonyhawk")),
    ("TopSpin", ("topspin",)),
    ("Train Sim World", ("train sim world",)),
    ("Transformers", ("transformers",)),
    ("Trine", ("trine ",)),
    ("Turok", ("turok",)),
    ("Two Point", ("two point",)),
    ("UFC", ("ufc ",)),
    ("Until Dawn", ("until dawn",)),
    ("Vampire: The Masquerade", ("vampire the masquerade", "vampire: the masquerade", "bloodlines 2")),
    ("Warhammer 40,000", ("warhammer 40", "inquisitor warhammer")),
    ("Warhammer Age of Sigmar", ("warhammer age of sigmar",)),
    ("Way of the Hunter", ("way of the hunter",)),
    ("White Day", ("white day",)),
    ("World of Goo", ("world of goo",)),
    ("World War Z", ("world war z",)),
    ("Worms", ("worms ",)),
    ("WRC", ("wrc ", "ea sports wrc")),
    ("Wreckfest", ("wreckfest",)),
    ("Yooka-Laylee", ("yooka",)),
    ("Yoshi", ("yoshi ", "yoshi's")),
    ("Zombie Army", ("zombie army", "zombi army")),
)


_PLATFORM = re.compile(r"^(?:PS[345]|NS2?|NSW|NINTENDO\s+SWITCH(?:\s+2)?|XBOX(?:\s+SERIES\s+X)?|XB1|XBX)\s+", re.I)
_CODE = re.compile(r"\b(?:CUSA|PPSA)\s*[-:]?\s*\d+\b|\s+\b(?:CUSA|PPSA)\b$", re.I)
_LANGUAGE = re.compile(r"\s*\((?:rus|eng|end|eur|uk|usa|eu|russian|english|arabic|multi|рус|англ|���)[^)]*\)", re.I)
_EDITION = re.compile(
    r"(?:\s*[-:]?\s*(?:standard|deluxe|gold|ultimate|complete|premium|collector'?s|collectors|"
    r"anniversary|limited|special|launch|day one|platinum|definitive|legendary|enhanced|royal|crew\s*mate|"
    r"game of the year|goty|director'?s cut|steelbook|lenticular|master|console|"
    r"physical|premium deluxe|digital deluxe|hd|remastered|remaster|remake)\s*(?:edition|version|collection)?)+$",
    re.I,
)


def clean_game_title(value):
    title = unicodedata.normalize("NFKC", str(value or ""))
    title = title.translate(str.maketrans({"’": "'", "‘": "'", "�": "'", "`": "'"}))
    title = _PLATFORM.sub("", title.strip())
    title = re.sub(r"^(?:VR2?|PSVR2?)\s+", "", title, flags=re.I)
    title = _CODE.sub("", title)
    title = _LANGUAGE.sub("", title)
    title = re.sub(r"\s*\(\)", "", title)
    title = re.sub(r"\s+Pegi\b", "", title, flags=re.I)
    title = re.sub(r"\s+\((?:1-2|eng|rus)\s+lang\)", "", title, flags=re.I)
    title = re.sub(r"\s+\([^)]*(?:disc|disk|диск|версия|издание)[^)]*\)", "", title, flags=re.I)
    title = re.sub(r"\s+(?:rus|eng)\s+(?:sub|lang)$", "", title, flags=re.I)
    title = normalize_game_series_name(title).strip(" -:")
    title = re.sub(r"\b[СC]reed\b", "Creed", title, flags=re.I)
    title = title.replace('"s ', "'s ")
    for _ in range(3):
        shorter = _EDITION.sub("", title).strip(" -:")
        if shorter == title or not shorter:
            break
        title = shorter
    return normalize_game_series_name(title).strip(" -:")


def classify_game_title(value):
    title = clean_game_title(value)
    folded = title.casefold()
    for canonical, aliases in CURATED_VARIANTS + FRANCHISE_ALIASES:
        if any(folded == alias.rstrip() or folded.startswith(alias) for alias in aliases):
            return canonical, "curated"
    return title or normalize_game_series_name(value), "standalone"
