# Generated by Django 5.2.17 on 2026-09-08 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_ensure_warehouse_cash_registers'),
        ('sales', '0002_sale_consignment_platform_alter_sale_price_type_and_more'),
        ('warehouse', '0003_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='operation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Ключ операции'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Внесение наличных'), ('collection', 'Инкассация'), ('sale_payment', 'Оплата продажи'), ('safe_deposit', 'Внесение в сейф'), ('safe_collection', 'Инкассация из сейфа'), ('cash_to_safe', 'Перевод: касса → сейф'), ('safe_to_cash', 'Перевод: сейф → касса')], max_length=24, verbose_name='Операция'),
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток наличных')),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='safe', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'сейф',
                'verbose_name_plural': 'сейфы',
                'permissions': [('deposit_safe', 'Может вносить наличные в сейф'), ('collect_safe', 'Может инкассировать наличные из сейфа'), ('transfer_cash_to_safe', 'Может переводить наличные из кассы в сейф'), ('transfer_safe_to_cash', 'Может переводить наличные из сейфа в кассу')],
            },
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='safe',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cash.safe', verbose_name='Сейф'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type__in', ('deposit', 'collection', 'sale_payment')), ('safe__isnull', True)), models.Q(('operation_type__in', ('safe_deposit', 'safe_collection', 'cash_to_safe', 'safe_to_cash')), ('safe__isnull', False)), _connector='OR'), name='cash_transaction_safe_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='safe',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='safe_balance_nonnegative'),
        ),
    ]
