# Generated by Django 5.2.17 on 2026-09-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_ensure_warehouse_safes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashtransaction',
            name='cash_transaction_safe_matches_type',
        ),
    ]
