# Generated by Django 5.2.17 on 2026-09-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_remove_cashtransaction_cash_transaction_safe_matches_type'),
        ('orders', '0001_initial'),
        ('sales', '0003_alter_sale_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='customer_order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='orders.customerprocurementorder', verbose_name='Закупочный заказ'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='order_adjustment',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_transaction', to='orders.orderadjustment', verbose_name='Корректировка заказа'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Внесение наличных'), ('collection', 'Инкассация'), ('sale_payment', 'Оплата продажи'), ('safe_deposit', 'Внесение в сейф'), ('safe_collection', 'Инкассация из сейфа'), ('cash_to_safe', 'Перевод: касса → сейф'), ('safe_to_cash', 'Перевод: сейф → касса'), ('order_prepayment', 'Предоплата закупочного заказа'), ('order_refund', 'Возврат по закупочному заказу'), ('order_postpayment', 'Постоплата закупочного заказа')], max_length=24, verbose_name='Операция'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type__in', ('deposit', 'collection', 'sale_payment')), ('safe__isnull', True)), models.Q(('operation_type__in', ('safe_deposit', 'safe_collection', 'cash_to_safe', 'safe_to_cash')), ('safe__isnull', False)), models.Q(('customer_order__isnull', False), ('operation_type__in', ('order_prepayment', 'order_refund', 'order_postpayment')), ('safe__isnull', True)), _connector='OR'), name='cash_transaction_safe_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_type', 'order_prepayment')), fields=('customer_order',), name='unique_customer_order_prepayment'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_type', 'order_postpayment')), fields=('customer_order',), name='unique_customer_order_postpayment'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type', 'order_refund'), ('order_adjustment__isnull', False)), models.Q(models.Q(('operation_type', 'order_refund'), _negated=True), ('order_adjustment__isnull', True)), _connector='OR'), name='order_refund_has_adjustment'),
        ),
    ]
