# Generated by Django 5.2.17 on 2026-09-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_cashtransaction_customer_order_and_more'),
        ('orders', '0002_initial'),
        ('sales', '0003_alter_sale_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashtransaction',
            name='cash_transaction_safe_matches_type',
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Внесение наличных'), ('collection', 'Инкассация'), ('sale_payment', 'Оплата продажи'), ('sale_refund', 'Возврат по отменённой продаже'), ('safe_deposit', 'Внесение в сейф'), ('safe_collection', 'Инкассация из сейфа'), ('cash_to_safe', 'Перевод: касса → сейф'), ('safe_to_cash', 'Перевод: сейф → касса'), ('order_prepayment', 'Предоплата закупочного заказа'), ('order_refund', 'Возврат по закупочному заказу'), ('order_postpayment', 'Постоплата закупочного заказа')], max_length=24, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='sale',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='sales.sale', verbose_name='Продажа'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type__in', ('deposit', 'collection', 'sale_payment', 'sale_refund')), ('safe__isnull', True)), models.Q(('operation_type__in', ('safe_deposit', 'safe_collection', 'cash_to_safe', 'safe_to_cash')), ('safe__isnull', False)), models.Q(('customer_order__isnull', False), ('operation_type__in', ('order_prepayment', 'order_refund', 'order_postpayment')), ('safe__isnull', True)), _connector='OR'), name='cash_transaction_safe_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_type__in', ('sale_payment', 'sale_refund')), ('sale__isnull', False)), fields=('sale', 'operation_type'), name='unique_sale_cash_operation_type'),
        ),
    ]
