# Generated by Django 5.2.17 on 2026-09-10 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_remove_cashtransaction_cash_transaction_safe_matches_type_and_more'),
        ('orders', '0002_initial'),
        ('sales', '0004_alter_sale_options_sale_cancellation_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type__in', ('sale_payment', 'sale_refund')), ('sale__isnull', False)), models.Q(models.Q(('operation_type__in', ('sale_payment', 'sale_refund')), _negated=True), ('sale__isnull', True)), _connector='OR'), name='sale_cash_operation_has_sale'),
        ),
    ]
