# Generated by Django 5.2.17 on 2026-09-01 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Принята')),
                ('status', models.CharField(choices=[('accepted', 'Принята')], default='accepted', editable=False, max_length=20, verbose_name='Статус')),
                ('total_units', models.PositiveIntegerField(verbose_name='Физических единиц')),
                ('goods_total_before_expenses', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Товары до расходов')),
                ('expenses_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Дополнительные расходы')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итого')),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'поставки',
                'ordering': ('-accepted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupplyCDItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('purchase_unit_cost', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Закупочная цена единицы')),
                ('allocated_expense_per_unit', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Расход на единицу')),
                ('effective_unit_cost', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Итоговая цена единицы')),
                ('base_line_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Закупочная сумма строки')),
                ('final_line_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итоговая сумма строки')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_sku_snapshot', models.CharField(max_length=100, verbose_name='Артикул')),
                ('supplier_letter_snapshot', models.CharField(max_length=8, verbose_name='Буква поставщика')),
                ('supplier_color_snapshot', models.CharField(max_length=7, verbose_name='Цвет поставщика')),
                ('supplier_name_snapshot', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='catalog.cd', verbose_name='CD')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Поставщик')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cd_items', to='supplies.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'позиция CD в поставке',
                'verbose_name_plural': 'позиции CD в поставках',
            },
        ),
        migrations.CreateModel(
            name='SupplyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='supplies.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'дополнительный расход',
                'verbose_name_plural': 'дополнительные расходы',
            },
        ),
        migrations.CreateModel(
            name='SupplyTechItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('purchase_unit_cost', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Закупочная цена единицы')),
                ('allocated_expense_per_unit', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Расход на единицу')),
                ('effective_unit_cost', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Итоговая цена единицы')),
                ('base_line_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Закупочная сумма строки')),
                ('final_line_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итоговая сумма строки')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_sku_snapshot', models.CharField(max_length=100, verbose_name='Артикул')),
                ('supplier_letter_snapshot', models.CharField(max_length=8, verbose_name='Буква поставщика')),
                ('supplier_color_snapshot', models.CharField(max_length=7, verbose_name='Цвет поставщика')),
                ('supplier_name_snapshot', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='catalog.tech', verbose_name='Техника')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.supplier', verbose_name='Поставщик')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_items', to='supplies.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'позиция техники в поставке',
                'verbose_name_plural': 'позиции техники в поставках',
            },
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('total_units__gt', 0)), name='supply_total_units_positive'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('goods_total_before_expenses__gte', 0)), name='supply_goods_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('expenses_total__gte', 0)), name='supply_expenses_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='supply_grand_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supply_cd_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_unit_cost__gte', 0)), name='supply_cd_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplyexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='supply_expense_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supply_tech_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_unit_cost__gte', 0)), name='supply_tech_cost_nonnegative'),
        ),
    ]
