# Generated by Django 5.2.17 on 2026-09-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_expense_per_unit__gte', 0)), name='supply_cd_allocated_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('effective_unit_cost__gte', 0)), name='supply_cd_effective_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('base_line_total__gte', 0)), name='supply_cd_base_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('final_line_total__gte', 0)), name='supply_cd_final_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_expense_per_unit__gte', 0)), name='supply_tech_allocated_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('effective_unit_cost__gte', 0)), name='supply_tech_effective_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('base_line_total__gte', 0)), name='supply_tech_base_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('final_line_total__gte', 0)), name='supply_tech_final_total_nonnegative'),
        ),
    ]
