# Generated by Django 5.2.17 on 2026-09-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_cd_barcode_alter_tech_barcode'),
        ('supplies', '0003_supply_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название товара')),
                ('product_sku_snapshot', models.CharField(editable=False, max_length=100, verbose_name='Артикул')),
                ('old_owned_quantity', models.PositiveIntegerField(editable=False, verbose_name='Количество до поставки')),
                ('old_unit_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Себестоимость до поставки')),
                ('old_inventory_value', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Стоимость остатка до поставки')),
                ('incoming_quantity', models.PositiveIntegerField(editable=False, verbose_name='Поступило')),
                ('incoming_value', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Стоимость поступления с расходами')),
                ('resulting_quantity', models.PositiveIntegerField(editable=False, verbose_name='Количество после поставки')),
                ('resulting_value', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Общая стоимость после поставки')),
                ('resulting_unit_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Новая себестоимость')),
                ('cd', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_cost_calculations', to='catalog.cd', verbose_name='CD')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_calculations', to='supplies.supply', verbose_name='Поставка')),
                ('tech', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_cost_calculations', to='catalog.tech', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'расчёт себестоимости поставки',
                'verbose_name_plural': 'расчёты себестоимости поставок',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='supply_cost_calculation_exact_product'), models.UniqueConstraint(condition=models.Q(('cd__isnull', False)), fields=('supply', 'cd'), name='unique_supply_cd_cost_calculation'), models.UniqueConstraint(condition=models.Q(('tech__isnull', False)), fields=('supply', 'tech'), name='unique_supply_tech_cost_calculation'), models.CheckConstraint(condition=models.Q(('incoming_quantity__gt', 0)), name='supply_cost_incoming_quantity_positive')],
            },
        ),
    ]
