# Generated by Django 5.2.17 on 2026-09-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_supplycostcalculation'),
        ('warehouse', '0003_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('-accepted_at', '-id'), 'permissions': [('cancel_supply', 'Может отменять принятые приходы')], 'verbose_name': 'поставка', 'verbose_name_plural': 'поставки'},
        ),
        migrations.AddField(
            model_name='supply',
            name='cancellation_comment',
            field=models.TextField(blank=True, editable=False, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='supply',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Отменена'),
        ),
        migrations.AddField(
            model_name='supply',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принята'), ('cancelled', 'Отменена')], default='accepted', editable=False, max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_comment', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'accepted')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_comment', ''), _negated=True)), _connector='OR'), name='supply_cancellation_fields_consistent'),
        ),
    ]
