# Generated by Django 5.2.17 on 2026-09-12 09:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_retail_price_to_avito_price'),
        ('partners', '0001_initial'),
        ('supplies', '0005_alter_supply_options_supply_cancellation_comment_and_more'),
        ('warehouse', '0004_alter_warehouse_options_warehousestoragelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='total_weight_grams',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Общий вес поставки, г'),
        ),
        migrations.AddField(
            model_name='supply',
            name='weight_transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Транспортные расходы по весу'),
        ),
        migrations.AddField(
            model_name='supplycditem',
            name='allocated_transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Транспортные расходы строки'),
        ),
        migrations.AddField(
            model_name='supplycditem',
            name='line_weight_grams',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Вес строки, г'),
        ),
        migrations.AddField(
            model_name='supplycditem',
            name='transport_cost_per_unit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Транспортные расходы на единицу'),
        ),
        migrations.AddField(
            model_name='supplycditem',
            name='weight_grams_snapshot',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Вес единицы на момент прихода, г'),
        ),
        migrations.AddField(
            model_name='supplytechitem',
            name='allocated_transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Транспортные расходы строки'),
        ),
        migrations.AddField(
            model_name='supplytechitem',
            name='line_weight_grams',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Вес строки, г'),
        ),
        migrations.AddField(
            model_name='supplytechitem',
            name='transport_cost_per_unit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Транспортные расходы на единицу'),
        ),
        migrations.AddField(
            model_name='supplytechitem',
            name='weight_grams_snapshot',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Вес единицы на момент прихода, г'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('weight_transport_cost__gte', 0)), name='supply_weight_transport_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(('total_weight_grams__gt', 0), ('total_weight_grams__isnull', True), _connector='OR'), name='supply_total_weight_positive_or_legacy'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams_snapshot__gt', 0), ('weight_grams_snapshot__isnull', True), _connector='OR'), name='supply_cd_weight_positive_or_legacy'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('line_weight_grams__gt', 0), ('line_weight_grams__isnull', True), _connector='OR'), name='supply_cd_line_weight_positive_or_legacy'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_transport_cost__gte', 0)), name='supply_cd_transport_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplycditem',
            constraint=models.CheckConstraint(condition=models.Q(('transport_cost_per_unit__gte', 0)), name='supply_cd_transport_unit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams_snapshot__gt', 0), ('weight_grams_snapshot__isnull', True), _connector='OR'), name='supply_tech_weight_positive_or_legacy'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_weight_grams__gt', 0), ('line_weight_grams__isnull', True), _connector='OR'), name='supply_tech_line_weight_positive_or_legacy'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_transport_cost__gte', 0)), name='supply_tech_transport_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplytechitem',
            constraint=models.CheckConstraint(condition=models.Q(('transport_cost_per_unit__gte', 0)), name='supply_tech_transport_unit_nonnegative'),
        ),
    ]
