# Generated by Django 5.2.17 on 2026-09-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cd_default_weight_120'),
        ('partners', '0001_initial'),
        ('supplies', '0006_supply_total_weight_grams_and_more'),
        ('warehouse', '0004_alter_warehouse_options_warehousestoragelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('-accepted_at', '-id'), 'permissions': [('cancel_supply', 'Может отменять принятые приходы'), ('edit_accepted_supply', 'Может редактировать принятые приходы')], 'verbose_name': 'поставка', 'verbose_name_plural': 'поставки'},
        ),
        migrations.AddField(
            model_name='supply',
            name='last_revised_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='supply',
            name='last_revised_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revised_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Последним изменил'),
        ),
        migrations.AddField(
            model_name='supply',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Текущая редакция'),
        ),
        migrations.CreateModel(
            name='SupplyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(editable=False, verbose_name='Номер редакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('reason', models.TextField(editable=False, verbose_name='Причина изменения')),
                ('accepted_at_snapshot', models.DateTimeField(editable=False, verbose_name='Историческая дата прихода')),
                ('accepted_by_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Принял')),
                ('total_units', models.PositiveIntegerField(editable=False, verbose_name='Физических единиц')),
                ('goods_total_before_expenses', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Товары до расходов')),
                ('expenses_total', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Дополнительные расходы')),
                ('weight_transport_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Транспортные расходы по весу')),
                ('total_weight_grams', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Общий вес, г')),
                ('grand_total', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Итого')),
                ('diff_summary', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Сводка изменений')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supply_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='supplies.supply', verbose_name='Приход')),
                ('warehouse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supply_revision_snapshots', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'редакция принятого прихода',
                'verbose_name_plural': 'редакции принятых приходов',
                'ordering': ('-revision_number', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupplyRevisionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='Название расхода')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Сумма')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='supplies.supplyrevision', verbose_name='Редакция')),
            ],
            options={
                'verbose_name': 'расход редакции прихода',
                'verbose_name_plural': 'расходы редакций приходов',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplyRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('quantity', models.PositiveIntegerField(editable=False, verbose_name='Количество')),
                ('purchase_unit_cost', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Закупка за единицу')),
                ('allocated_expense_per_unit', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Обычный расход за единицу')),
                ('weight_grams_snapshot', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Вес единицы, г')),
                ('line_weight_grams', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='Вес строки, г')),
                ('allocated_transport_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Транспорт строки')),
                ('transport_cost_per_unit', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Транспорт за единицу')),
                ('effective_unit_cost', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Итог за единицу')),
                ('base_line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Закупка строки')),
                ('final_line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Итого строки')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название товара')),
                ('product_sku_snapshot', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Артикул')),
                ('supplier_letter_snapshot', models.CharField(editable=False, max_length=8, verbose_name='Буква поставщика')),
                ('supplier_color_snapshot', models.CharField(editable=False, max_length=7, verbose_name='Цвет поставщика')),
                ('supplier_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название поставщика')),
                ('cd', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cd')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.supplyrevision', verbose_name='Редакция')),
                ('supplier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='partners.supplier')),
                ('tech', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.tech')),
            ],
            options={
                'verbose_name': 'позиция редакции прихода',
                'verbose_name_plural': 'позиции редакций приходов',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='supplyrevision',
            constraint=models.UniqueConstraint(fields=('supply', 'revision_number'), name='unique_supply_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='supplyrevisionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='supply_revision_item_exact_product'),
        ),
    ]
