# Generated by Django 5.2.17 on 2026-09-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productchangeevent_action_kind'),
        ('supplies', '0007_alter_supply_options_supply_last_revised_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('-accepted_at', '-id'), 'permissions': [('cancel_supply', 'Может отменять принятые приходы'), ('edit_accepted_supply', 'Может редактировать принятые приходы'), ('finalize_supply', 'Может выполнять финализацию прихода')], 'verbose_name': 'поставка', 'verbose_name_plural': 'поставки'},
        ),
        migrations.CreateModel(
            name='SupplyFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('supply_revision_number', models.PositiveIntegerField(editable=False, verbose_name='Редакция прихода')),
                ('total_penalty_before_distribution', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Неустойка до автораспределения')),
                ('status', models.CharField(choices=[('applied', 'Применена'), ('superseded', 'Утратила актуальность после редакции прихода')], default='applied', editable=False, max_length=20, verbose_name='Статус')),
                ('superseded_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Утратила актуальность')),
                ('superseded_by_revision_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Заменена редакцией')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='supply_finalizations', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalizations', to='supplies.supply', verbose_name='Приход')),
            ],
            options={
                'verbose_name': 'финализация прихода',
                'verbose_name_plural': 'финализации приходов',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupplyFinalizationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название товара')),
                ('product_sku_snapshot', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Артикул')),
                ('global_quantity_snapshot', models.PositiveIntegerField(editable=False, verbose_name='Глобальный остаток')),
                ('old_global_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Старая себестоимость')),
                ('new_global_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Новая себестоимость')),
                ('difference_per_unit', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Изменение на единицу')),
                ('value_difference', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Изменение стоимости остатка')),
                ('change_source', models.CharField(choices=[('manual', 'Вручную'), ('auto', 'Автораспределение')], editable=False, max_length=8, verbose_name='Способ изменения')),
                ('cd', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_finalization_items', to='catalog.cd', verbose_name='CD')),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='supplies.supplyfinalization', verbose_name='Финализация')),
                ('tech', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_finalization_items', to='catalog.tech', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'позиция финализации прихода',
                'verbose_name_plural': 'позиции финализации приходов',
                'ordering': ('product_kind', 'product_name_snapshot', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='supplyfinalization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'applied'), ('superseded_at__isnull', True), ('superseded_by_revision_number__isnull', True)), models.Q(('status', 'superseded'), ('superseded_at__isnull', False), ('superseded_by_revision_number__isnull', False)), _connector='OR'), name='supply_finalization_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='supplyfinalizationitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='supply_finalization_item_exact_product'),
        ),
        migrations.AddConstraint(
            model_name='supplyfinalizationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('cd__isnull', False)), fields=('finalization', 'cd'), name='unique_supply_finalization_cd'),
        ),
        migrations.AddConstraint(
            model_name='supplyfinalizationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('tech__isnull', False)), fields=('finalization', 'tech'), name='unique_supply_finalization_tech'),
        ),
        migrations.AddConstraint(
            model_name='supplyfinalizationitem',
            constraint=models.CheckConstraint(condition=models.Q(('old_global_cost__gte', 0)), name='supply_finalization_old_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplyfinalizationitem',
            constraint=models.CheckConstraint(condition=models.Q(('new_global_cost__gte', 0)), name='supply_finalization_new_cost_nonnegative'),
        ),
    ]
