# Generated by Django 5.2.17 on 2026-09-28 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_warehouse_cost_labels'),
        ('warehouse', '0005_transfer_cost_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supply',
            name='supply_cancellation_fields_consistent',
        ),
        migrations.AddField(
            model_name='supply',
            name='price_reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Цены подтверждены'),
        ),
        migrations.AddField(
            model_name='supply',
            name='price_reviewed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_supply_prices', to=settings.AUTH_USER_MODEL, verbose_name='Цены подтвердил'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('price_review', 'Требуется проверка цен'), ('accepted', 'Принята'), ('cancelled', 'Отменена')], default='accepted', editable=False, max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='supply',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_comment', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'accepted')), models.Q(('cancellation_comment', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'price_review')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_comment', ''), _negated=True)), _connector='OR'), name='supply_cancellation_fields_consistent'),
        ),
    ]
