# Generated by Django 5.2.17 on 2026-09-15 08:08

import django.db.models.deletion
import integrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_alter_productchangeevent_action_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoRemoteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_item_id', models.PositiveBigIntegerField(unique=True, verbose_name='Avito ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('category_name', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('status', models.CharField(blank=True, max_length=64, verbose_name='Статус')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('snapshot', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Безопасный snapshot')),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последний раз получено')),
                ('missing_since', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Не найдено с')),
            ],
            options={
                'verbose_name': 'объявление Avito',
                'verbose_name_plural': 'объявления Avito',
                'ordering': ('-last_seen_at', '-avito_item_id'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('avito', 'Avito')], max_length=32, unique=True, verbose_name='Интеграция')),
                ('encrypted_client_id', models.TextField(blank=True, editable=False, verbose_name='Client ID (зашифрован)')),
                ('encrypted_client_secret', models.TextField(blank=True, editable=False, verbose_name='Client secret (зашифрован)')),
                ('account_id', models.CharField(blank=True, editable=False, max_length=64, verbose_name='ID аккаунта')),
                ('account_name', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Название аккаунта')),
                ('status', models.CharField(choices=[('not_configured', 'Не настроено'), ('connected', 'Подключено'), ('error', 'Ошибка подключения')], default='not_configured', editable=False, max_length=24, verbose_name='Состояние')),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последняя проверка')),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последнее успешное подключение')),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Последняя ошибка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'параметры интеграции',
                'verbose_name_plural': 'параметры интеграций',
                'permissions': [('view_integrations', 'Интеграции: просмотр'), ('manage_integration_credentials', 'Интеграции: изменение API-ключей'), ('view_avito_integration', 'Avito: просмотр'), ('manage_avito_product', 'Avito: изменение профиля товара'), ('bind_avito_listing', 'Avito: привязка объявления'), ('rebind_avito_listing', 'Avito: перепривязка объявления'), ('manual_avito_sync', 'Avito: ручная синхронизация')],
            },
        ),
        migrations.CreateModel(
            name='AvitoProductProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_on_avito', models.BooleanField(default=False, verbose_name='Продаётся на Avito')),
                ('listing_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок Avito')),
                ('listing_description', models.TextField(blank=True, verbose_name='Описание Avito')),
                ('category_slug', models.CharField(blank=True, max_length=255, verbose_name='Категория Avito')),
                ('category_name', models.CharField(blank=True, max_length=255, verbose_name='Название категории')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Поля Avito')),
                ('schema_snapshot', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Схема полей Avito')),
                ('sync_status', models.CharField(choices=[('idle', 'Ожидает'), ('queued', 'В очереди'), ('syncing', 'Синхронизация'), ('ok', 'OK'), ('error', 'Ошибка')], default='idle', editable=False, max_length=16, verbose_name='Состояние синхронизации')),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Последняя ошибка')),
                ('last_successful_sync_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последняя успешная синхронизация')),
                ('desired_state_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Хэш состояния')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('cd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avito_profile', to='catalog.cd')),
                ('tech', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avito_profile', to='catalog.tech')),
            ],
            options={
                'verbose_name': 'Avito-профиль товара',
                'verbose_name_plural': 'Avito-профили товаров',
            },
        ),
        migrations.CreateModel(
            name='AvitoProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=integrations.models.avito_photo_upload_to, verbose_name='Фотография')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('source', models.CharField(choices=[('user', 'Загружено пользователем'), ('avito', 'Импортировано из Avito')], default='user', max_length=16, verbose_name='Источник')),
                ('remote_url', models.URLField(blank=True, editable=False, max_length=1000, verbose_name='Исходный URL Avito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='integrations.avitoproductprofile', verbose_name='Avito-профиль')),
            ],
            options={
                'verbose_name': 'Avito-фотография',
                'verbose_name_plural': 'Avito-фотографии',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AvitoListingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='integrations.avitoproductprofile', verbose_name='Профиль товара')),
                ('remote_listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='connection', to='integrations.avitoremotelisting', verbose_name='Объявление Avito')),
            ],
            options={
                'verbose_name': 'привязка объявления Avito',
                'verbose_name_plural': 'привязки объявлений Avito',
            },
        ),
        migrations.CreateModel(
            name='AvitoSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ объединения')),
                ('job_type', models.CharField(choices=[('product', 'Товар'), ('reconcile', 'Контрольная сверка'), ('refresh', 'Обновление объявлений')], max_length=16, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Выполнено'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('run_after', models.DateTimeField(verbose_name='Выполнить после')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.avitoproductprofile')),
            ],
            options={
                'verbose_name': 'задача синхронизации Avito',
                'verbose_name_plural': 'задачи синхронизации Avito',
                'ordering': ('run_after', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AvitoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=64, verbose_name='Операция')),
                ('result', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('skipped', 'Пропущено')], max_length=16, verbose_name='Результат')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP-статус')),
                ('error_category', models.CharField(blank=True, max_length=32, verbose_name='Категория ошибки')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('retry_number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер попытки')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершение')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='integrations.avitoproductprofile')),
                ('remote_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='integrations.avitoremotelisting')),
            ],
            options={
                'verbose_name': 'запись синхронизации Avito',
                'verbose_name_plural': 'журнал синхронизации Avito',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('product_kind', models.CharField(blank=True, max_length=8, verbose_name='Тип товара')),
                ('product_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID товара')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали без секретов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'событие интеграции',
                'verbose_name_plural': 'аудит интеграций',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='avitoproductprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('tech__isnull', False)), _connector='OR'), name='avito_profile_exact_product'),
        ),
        migrations.AddConstraint(
            model_name='avitoproductphoto',
            constraint=models.UniqueConstraint(fields=('profile', 'sort_order'), name='unique_avito_photo_order'),
        ),
        migrations.AddIndex(
            model_name='avitosyncjob',
            index=models.Index(fields=['status', 'run_after'], name='avito_job_due_idx'),
        ),
    ]
