# Generated by Django 5.2.17 on 2026-09-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitoremotelisting',
            name='remote_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='Текущая цена Avito'),
        ),
    ]
