# Generated by Django 5.2.17 on 2026-09-28 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_avito_status_refresh_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_url', models.URLField(max_length=1000, verbose_name='Ссылка на таблицу')),
                ('spreadsheet_id', models.CharField(editable=False, max_length=255, verbose_name='ID таблицы')),
                ('sheet_name', models.CharField(default='Прайс CRM', max_length=100, verbose_name='Лист CRM')),
                ('enabled', models.BooleanField(default=True, verbose_name='Автоматическая синхронизация')),
                ('status', models.CharField(choices=[('not_configured', 'Не настроено'), ('idle', 'Ожидает'), ('queued', 'В очереди'), ('syncing', 'Синхронизация'), ('ok', 'Синхронизировано'), ('error', 'Ошибка')], default='idle', max_length=24, verbose_name='Состояние')),
                ('last_attempt_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последняя попытка')),
                ('last_success_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последняя успешная синхронизация')),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Последняя ошибка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'интеграция Google Sheets',
                'verbose_name_plural': 'интеграция Google Sheets',
                'permissions': [('manual_google_sheets_sync', 'Google Sheets: ручная синхронизация')],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ объединения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Выполнено'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('run_after', models.DateTimeField(verbose_name='Выполнить после')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_sheets_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('run_after', 'id'),
                'indexes': [models.Index(fields=['status', 'run_after'], name='google_sheet_job_due_idx')],
            },
        ),
    ]
