# Generated by Django 5.2.17 on 2026-10-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_googlesheetsintegration_googlesheetssyncjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReefApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(blank=True, editable=False, verbose_name='API key (зашифрован)')),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последняя проверка')),
                ('last_error', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Ошибка подключения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'ключ ReefAPI',
                'verbose_name_plural': 'ключи ReefAPI',
            },
        ),
        migrations.CreateModel(
            name='AvitoPriceCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(verbose_name='Время проверки')),
                ('offers', models.JSONField(default=list, verbose_name='Подходящие объявления')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_check_result', to='integrations.avitoproductprofile', verbose_name='Профиль товара')),
            ],
            options={
                'verbose_name': 'результат Avito Check',
                'verbose_name_plural': 'результаты Avito Check',
            },
        ),
    ]
