# Generated by Django 5.2.17 on 2026-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_reefapicredential_avitopricecheckresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoCheckListingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=32, unique=True, verbose_name='ID объявления')),
                ('checked_at', models.DateTimeField(verbose_name='Время получения')),
                ('data', models.JSONField(default=dict, verbose_name='Карточка ReefAPI')),
            ],
            options={
                'verbose_name': 'кеш объявления Avito Check',
                'verbose_name_plural': 'кеш объявлений Avito Check',
            },
        ),
        migrations.AddField(
            model_name='avitopricecheckresult',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры проверки'),
        ),
    ]
