# Generated by Django 5.2.17 on 2026-10-04 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_avito_check_economy_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoManualPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Найденная минимальная цена')),
                ('recorded_at', models.DateTimeField(verbose_name='Дата добавления')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_price', to='integrations.avitoproductprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'найденная цена Avito',
                'verbose_name_plural': 'найденные цены Avito',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='avito_manual_price_positive')],
            },
        ),
    ]
