# Generated by Django 5.2.17 on 2026-09-01 21:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'платформа',
                'verbose_name_plural': 'платформы',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'типы товара',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sku', models.CharField(max_length=100, verbose_name='Артикул')),
                ('barcode', models.CharField(max_length=100, verbose_name='Штрихкод')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('quantity_on_consignment', models.PositiveIntegerField(default=0, editable=False, verbose_name='На реализации')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя себестоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cusa_ppsa_code', models.CharField(blank=True, max_length=100, verbose_name='CUSA/PPSA код')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cds', to='catalog.platform', verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'CD',
                'verbose_name_plural': 'CD',
                'ordering': ('name', 'id'),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='cd_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('quantity_on_consignment__gte', 0)), name='cd_consignment_nonnegative'), models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='cd_cost_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sku', models.CharField(max_length=100, verbose_name='Артикул')),
                ('barcode', models.CharField(max_length=100, verbose_name='Штрихкод')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('quantity_on_consignment', models.PositiveIntegerField(default=0, editable=False, verbose_name='На реализации')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средняя себестоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_items', to='catalog.brand', verbose_name='Бренд')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_items', to='catalog.producttype', verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'техника',
                'verbose_name_plural': 'техника',
                'ordering': ('name', 'id'),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='tech_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('quantity_on_consignment__gte', 0)), name='tech_consignment_nonnegative'), models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='tech_cost_nonnegative')],
            },
        ),
    ]
