# Generated by Django 5.2.17 on 2026-09-05 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cost_two_decimal_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd',
            options={'ordering': ('name', 'id'), 'permissions': [('view_nomenclature', 'Номенклатура: просмотр'), ('change_cd_platform', 'CD: изменение платформы'), ('change_cd_name', 'CD: изменение названия'), ('change_cd_description', 'CD: изменение описания'), ('change_cd_sku', 'CD: изменение артикула'), ('change_cd_barcode', 'CD: изменение штрихкода'), ('change_cd_cusa_ppsa_code', 'CD: изменение CUSA/PPSA'), ('change_cd_comment', 'CD: изменение комментария')], 'verbose_name': 'CD', 'verbose_name_plural': 'CD'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ('name', 'id'), 'permissions': [('change_tech_brand', 'Tech: изменение бренда'), ('change_tech_product_type', 'Tech: изменение типа товара'), ('change_tech_name', 'Tech: изменение названия'), ('change_tech_description', 'Tech: изменение описания'), ('change_tech_sku', 'Tech: изменение артикула'), ('change_tech_barcode', 'Tech: изменение штрихкода'), ('change_tech_comment', 'Tech: изменение комментария')], 'verbose_name': 'техника', 'verbose_name_plural': 'техника'},
        ),
        migrations.CreateModel(
            name='ProductChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('source', models.CharField(choices=[('crm', 'CRM'), ('django_admin', 'Django Admin')], editable=False, max_length=24, verbose_name='Источник')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('actor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_change_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('cd', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='catalog.cd', verbose_name='CD')),
                ('tech', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_events', to='catalog.tech', verbose_name='Tech')),
            ],
            options={
                'verbose_name': 'событие изменения товара',
                'verbose_name_plural': 'история изменений товаров',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductFieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(editable=False, max_length=100, verbose_name='Поле')),
                ('field_label', models.CharField(editable=False, max_length=255, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, editable=False, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, editable=False, verbose_name='Новое значение')),
                ('event', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='catalog.productchangeevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'изменение поля товара',
                'verbose_name_plural': 'изменения полей товаров',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='productchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='product_change_event_exact_product'),
        ),
    ]
