# Generated by Django 5.2.17 on 2026-09-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cd_options_alter_tech_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeevent',
            name='action_kind',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('warehouse_transfer', 'Перемещение'), ('consignment', 'Реализация'), ('supply', 'Поставка')], editable=False, max_length=32, verbose_name='Тип связанного действия'),
        ),
        migrations.AddField(
            model_name='productchangeevent',
            name='action_label',
            field=models.CharField(blank=True, editable=False, max_length=120, verbose_name='Номер связанного действия'),
        ),
        migrations.AddField(
            model_name='productchangeevent',
            name='action_object_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='ID связанного действия'),
        ),
        migrations.AlterField(
            model_name='productchangeevent',
            name='actor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_change_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='productchangeevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_kind', ''), ('action_label', ''), ('action_object_id__isnull', True)), models.Q(models.Q(('action_kind', ''), _negated=True), ('action_object_id__isnull', False), models.Q(('action_label', ''), _negated=True)), _connector='OR'), name='product_change_event_valid_action'),
        ),
    ]
