# Generated by Django 5.2.17 on 2026-09-05 12:30

from django.db import migrations, models


def mark_existing_nomenclature_events(apps, schema_editor):
    ProductChangeEvent = apps.get_model('catalog', 'ProductChangeEvent')
    ProductChangeEvent.objects.filter(source='crm', action_kind='').update(source='nomenclature')


def restore_legacy_source(apps, schema_editor):
    ProductChangeEvent = apps.get_model('catalog', 'ProductChangeEvent')
    ProductChangeEvent.objects.filter(source='nomenclature').update(source='crm')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productchangeevent_action_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchangeevent',
            name='source',
            field=models.CharField(choices=[('nomenclature', 'Номенклатура'), ('crm', 'CRM'), ('django_admin', 'Django Admin')], editable=False, max_length=24, verbose_name='Источник'),
        ),
        migrations.RunPython(mark_existing_nomenclature_events, restore_legacy_source),
    ]
