# Generated by Django 5.2.17 on 2026-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productchangeevent_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Штрихкод'),
        ),
    ]
