# Generated by Django 5.2.17 on 2026-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cd_default_weight_120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchangeevent',
            name='action_kind',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('warehouse_transfer', 'Перемещение'), ('consignment', 'Реализация'), ('supply', 'Поставка'), ('supply_finalization', 'Финализация прихода')], editable=False, max_length=32, verbose_name='Тип связанного действия'),
        ),
    ]
