# Generated by Django 5.2.17 on 2026-09-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productchangeevent_action_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Нормализованное название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'игровая серия',
                'verbose_name_plural': 'игровые серии',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='cd',
            options={'ordering': ('name', 'id'), 'permissions': [('view_nomenclature', 'Номенклатура: просмотр'), ('change_cd_platform', 'CD: изменение платформы'), ('change_cd_game_series', 'CD: изменение игровой серии'), ('change_cd_name', 'CD: изменение названия'), ('change_cd_description', 'CD: изменение описания'), ('change_cd_sku', 'CD: изменение артикула'), ('change_cd_barcode', 'CD: изменение штрихкода'), ('change_cd_weight', 'CD: изменение веса'), ('change_cd_cusa_ppsa_code', 'CD: изменение CUSA/PPSA'), ('change_cd_comment', 'CD: изменение комментария')], 'verbose_name': 'CD', 'verbose_name_plural': 'CD'},
        ),
        migrations.AddField(
            model_name='cd',
            name='game_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cds', to='catalog.gameseries', verbose_name='Игровая серия'),
        ),
    ]
