# Generated by Django 5.2.17 on 2026-09-17 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_gameseries_alter_cd_options_cd_game_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='cd',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалён'),
        ),
        migrations.AddField(
            model_name='cd',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён из активной номенклатуры'),
        ),
        migrations.AddField(
            model_name='tech',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='tech',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалён'),
        ),
        migrations.AddField(
            model_name='tech',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён из активной номенклатуры'),
        ),
        migrations.CreateModel(
            name='ProductRemovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hard_delete', 'Безвозвратное удаление'), ('archive', 'Удаление с сохранением истории')], max_length=16, verbose_name='Действие')),
                ('product_kind', models.CharField(max_length=8, verbose_name='Тип товара')),
                ('product_id', models.PositiveBigIntegerField(verbose_name='ID товара')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_removal_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'удаление товара',
                'verbose_name_plural': 'удаления товаров',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
