# Generated by Django 5.2.17 on 2026-09-28 14:07

from django.db import migrations, models
from django.db.models import Sum
from django.utils import timezone


def initialize_zero_stock_since(apps, schema_editor):
    now = timezone.now()
    for model_name in ("CD", "Tech"):
        model = apps.get_model("catalog", model_name)
        zero_ids = [
            row.pk for row in model.objects.annotate(total=Sum("warehouse_stocks__quantity"))
            if not (row.total or 0)
        ]
        model.objects.filter(pk__in=zero_ids).update(zero_stock_since=now)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_dedupe_platform_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='zero_stock_since',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Нулевой складской остаток с'),
        ),
        migrations.AddField(
            model_name='tech',
            name='zero_stock_since',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Нулевой складской остаток с'),
        ),
        migrations.RunPython(initialize_zero_stock_since, migrations.RunPython.noop),
    ]
