# Generated by Django 5.2.17 on 2026-10-01 10:18

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_cd_zero_stock_since_tech_zero_stock_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd',
            options={'ordering': ('name', 'id'), 'permissions': [('view_nomenclature', 'Номенклатура: просмотр'), ('change_cd_platform', 'CD: изменение платформы'), ('change_cd_game_series', 'CD: изменение игровой серии'), ('change_cd_name', 'CD: изменение названия'), ('change_cd_description', 'CD: изменение описания'), ('change_cd_sku', 'CD: изменение артикула'), ('change_cd_barcode', 'CD: изменение штрихкода'), ('change_cd_weight', 'CD: изменение веса'), ('change_cd_cusa_ppsa_code', 'CD: изменение CUSA/PPSA'), ('change_cd_comment', 'CD: изменение комментария'), ('change_cd_media', 'CD: изменение изображений')], 'verbose_name': 'CD', 'verbose_name_plural': 'CD'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ('name', 'id'), 'permissions': [('change_tech_brand', 'Tech: изменение бренда'), ('change_tech_product_type', 'Tech: изменение типа товара'), ('change_tech_name', 'Tech: изменение названия'), ('change_tech_description', 'Tech: изменение описания'), ('change_tech_sku', 'Tech: изменение артикула'), ('change_tech_barcode', 'Tech: изменение штрихкода'), ('change_tech_weight', 'Tech: изменение веса'), ('change_tech_comment', 'Tech: изменение комментария'), ('change_tech_media', 'Tech: изменение изображений')], 'verbose_name': 'техника', 'verbose_name_plural': 'техника'},
        ),
        migrations.AddField(
            model_name='cd',
            name='title_image',
            field=models.ImageField(blank=True, upload_to=catalog.models.product_title_image_upload_to, verbose_name='Титульное фото'),
        ),
        migrations.AddField(
            model_name='tech',
            name='title_image',
            field=models.ImageField(blank=True, upload_to=catalog.models.product_title_image_upload_to, verbose_name='Титульное фото'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], max_length=8, verbose_name='Тип товара')),
                ('image_kind', models.CharField(choices=[('additional', 'Дополнительное фото'), ('product', 'Изображение продукта')], max_length=16, verbose_name='Категория')),
                ('image', models.ImageField(upload_to=catalog.models.product_gallery_image_upload_to, verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_images', to='catalog.cd', verbose_name='CD')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_images', to='catalog.tech', verbose_name='Tech')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товаров',
                'ordering': ('image_kind', 'sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='product_image_exact_product')],
            },
        ),
    ]
