# Generated by Django 5.2.17 on 2026-10-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='wholesale_site_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Публиковать на оптовой витрине'),
        ),
        migrations.AddField(
            model_name='tech',
            name='wholesale_site_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Публиковать на оптовой витрине'),
        ),
    ]
