# Generated by Django 5.2.17 on 2026-10-09 15:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_supplier_template_exclusion'),
        ('yandex_market', '0003_categoryschema_name_categoryschema_placement_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Высота упаковки, см'),
        ),
        migrations.AddField(
            model_name='cd',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Длина упаковки, см'),
        ),
        migrations.AddField(
            model_name='cd',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Ширина упаковки, см'),
        ),
        migrations.AddField(
            model_name='cd',
            name='yandex_calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='Рассчитанная цена FBS, ₽'),
        ),
        migrations.AddField(
            model_name='cd',
            name='yandex_desired_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Желаемая чистая прибыль, ₽'),
        ),
        migrations.AddField(
            model_name='cd',
            name='yandex_pricing_category',
            field=models.ForeignKey(blank=True, help_text='У связанного товара используется категория его карточки Маркета.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='yandex_market.categoryschema', verbose_name='Категория для расчёта FBS'),
        ),
        migrations.AddField(
            model_name='cd',
            name='yandex_pricing_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='yandex_market.integration', verbose_name='Подключение для расчёта FBS'),
        ),
        migrations.AddField(
            model_name='tech',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Высота упаковки, см'),
        ),
        migrations.AddField(
            model_name='tech',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Длина упаковки, см'),
        ),
        migrations.AddField(
            model_name='tech',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Ширина упаковки, см'),
        ),
        migrations.AddField(
            model_name='tech',
            name='yandex_calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='Рассчитанная цена FBS, ₽'),
        ),
        migrations.AddField(
            model_name='tech',
            name='yandex_desired_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Желаемая чистая прибыль, ₽'),
        ),
        migrations.AddField(
            model_name='tech',
            name='yandex_pricing_category',
            field=models.ForeignKey(blank=True, help_text='У связанного товара используется категория его карточки Маркета.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='yandex_market.categoryschema', verbose_name='Категория для расчёта FBS'),
        ),
        migrations.AddField(
            model_name='tech',
            name='yandex_pricing_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='yandex_market.integration', verbose_name='Подключение для расчёта FBS'),
        ),
    ]
