# Generated by Django 5.2.17 on 2026-10-09 16:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_cd_height_cm_cd_length_cm_cd_width_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('4'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Высота упаковки, см'),
        ),
        migrations.AlterField(
            model_name='cd',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('23'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Длина упаковки, см'),
        ),
        migrations.AlterField(
            model_name='cd',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('15'), max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Ширина упаковки, см'),
        ),
    ]
