# Generated by Django 5.2.17 on 2026-10-03 09:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0022_cd_wholesale_site_enabled_and_more'),
        ('sales', '0014_merge_wholesale_sale_types'),
        ('warehouse', '0005_transfer_cost_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'подборка витрины',
                'verbose_name_plural': 'подборки витрины',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WholesaleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Контактное имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Основной номер телефона')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'оптовый контакт',
                'verbose_name_plural': 'оптовые контакты',
                'ordering': ('name', 'id'),
                'permissions': [('manage_wholesale_contacts', 'Управление контактами оптовой витрины')],
            },
        ),
        migrations.CreateModel(
            name='NewsCDProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cd')),
            ],
        ),
        migrations.CreateModel(
            name='StorefrontNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('cover', models.ImageField(blank=True, upload_to='resource/news/')),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='storefront_news', through='resource_storefront.NewsCDProduct', to='catalog.cd')),
            ],
            options={
                'verbose_name': 'новость витрины',
                'verbose_name_plural': 'новости витрины',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NewsTechProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tech')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_storefront.storefrontnews')),
            ],
        ),
        migrations.AddField(
            model_name='newscdproduct',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_storefront.storefrontnews'),
        ),
        migrations.CreateModel(
            name='StorefrontSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальная сумма заказа')),
                ('hero_title', models.CharField(blank=True, max_length=220, verbose_name='Заголовок главной')),
                ('hero_description', models.TextField(blank=True, verbose_name='Описание главной')),
                ('hero_button_label', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('hero_button_url', models.CharField(blank=True, max_length=300, verbose_name='Адрес кнопки')),
                ('hero_image_desktop', models.ImageField(blank=True, upload_to='resource/hero/')),
                ('hero_image_mobile', models.ImageField(blank=True, upload_to='resource/hero/')),
                ('about_text', models.TextField(blank=True, verbose_name='О бренде')),
                ('wholesale_terms', models.TextField(blank=True, verbose_name='Условия оптовой работы')),
                ('public_contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Склад витрины')),
            ],
            options={
                'verbose_name': 'настройки оптовой витрины',
                'verbose_name_plural': 'настройки оптовой витрины',
                'permissions': [('manage_storefront', 'Управление содержимым оптовой витрины')],
            },
        ),
        migrations.CreateModel(
            name='CollectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_slots', to='catalog.cd')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_slots', to='catalog.tech')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resource_storefront.productcollection')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('tech__isnull', False)), _connector='OR'), name='resource_collection_exact_product')],
            },
        ),
        migrations.CreateModel(
            name='StorefrontProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('new', 'Новинки'), ('home', 'Главная подборка')], max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefront_slots', to='catalog.cd')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefront_slots', to='catalog.tech')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('tech__isnull', False)), _connector='OR'), name='resource_slot_exact_product'), models.UniqueConstraint(condition=models.Q(('cd__isnull', False)), fields=('placement', 'cd'), name='resource_slot_unique_cd'), models.UniqueConstraint(condition=models.Q(('tech__isnull', False)), fields=('placement', 'tech'), name='resource_slot_unique_tech')],
            },
        ),
        migrations.CreateModel(
            name='WholesaleAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('encrypted_token', models.TextField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_links_created', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_links', to='resource_storefront.wholesalecontact')),
            ],
            options={
                'verbose_name': 'ссылка оптового доступа',
                'verbose_name_plural': 'ссылки оптового доступа',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contact',), name='resource_one_active_link_per_contact')],
            },
        ),
        migrations.CreateModel(
            name='StorefrontSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64)),
                ('cart_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storefront_submission', to='sales.sale')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='resource_storefront.wholesalecontact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact', 'idempotency_key'), name='resource_submission_once_per_contact')],
            },
        ),
    ]
