# Generated by Django 5.2.17 on 2026-10-03 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_cd_wholesale_site_enabled_and_more'),
        ('resource_storefront', '0002_initialize_storefront_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImageCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.CharField(editable=False, max_length=300)),
                ('position_x', models.PositiveSmallIntegerField(default=50, help_text='0 — слева, 50 — центр, 100 — справа.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Фокус по горизонтали, %')),
                ('position_y', models.PositiveSmallIntegerField(default=50, help_text='0 — сверху, 50 — центр, 100 — снизу.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Фокус по вертикали, %')),
                ('zoom', models.DecimalField(decimal_places=2, default=1, help_text='1 — обычное заполнение 3:4. Увеличивайте только для конкретного фото с лишними полями.', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Масштаб')),
                ('cd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.cd', verbose_name='Диск')),
                ('tech', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.tech', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'кадрирование фото каталога',
                'verbose_name_plural': 'кадрирование фото каталога',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('tech__isnull', False)), _connector='OR'), name='resource_crop_exact_product'), models.CheckConstraint(condition=models.Q(('position_x__lte', 100), ('position_y__lte', 100), ('zoom__gte', 1), ('zoom__lte', 3)), name='resource_crop_bounds')],
            },
        ),
    ]
