# Generated by Django 5.2.17 on 2026-10-03 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_storefront', '0003_catalogimagecrop'),
        ('sales', '0015_sale_buyer_address_snapshot_sale_buyer_comment_and_more'),
        ('warehouse', '0005_transfer_cost_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('price_source', models.CharField(choices=[('avito_price', 'Цена Avito')], default='avito_price', max_length=24, verbose_name='Источник цены')),
                ('generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('encrypted_token', models.TextField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Склад розничного сайта')),
            ],
            options={
                'verbose_name': 'настройки розничной витрины',
                'verbose_name_plural': 'настройки розничной витрины',
                'permissions': [('manage_retail_storefront', 'Управление розничной витриной и общей ссылкой')],
            },
        ),
        migrations.CreateModel(
            name='RetailSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField()),
                ('idempotency_key', models.UUIDField()),
                ('cart_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_submission', to='sales.sale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visitor_id', 'idempotency_key'), name='resource_retail_submission_once')],
            },
        ),
    ]
