# Generated by Django 5.2.17 on 2026-09-01 21:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDConsignmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reward_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вознаграждение за единицу')),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_stocks', to='catalog.cd', verbose_name='CD')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.salesplatform', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'остаток CD на реализации',
                'verbose_name_plural': 'остатки CD на реализации',
                'permissions': [('transfer_stock', 'Может передавать товар на реализацию'), ('return_stock', 'Может возвращать товар с реализации')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'cd'), name='unique_cd_platform_stock'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='cd_stock_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('reward_per_unit__gte', 0)), name='cd_stock_reward_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='TechConsignmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('reward_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вознаграждение за единицу')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.salesplatform', verbose_name='Площадка')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_stocks', to='catalog.tech', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'остаток техники на реализации',
                'verbose_name_plural': 'остатки техники на реализации',
                'constraints': [models.UniqueConstraint(fields=('platform', 'tech'), name='unique_tech_platform_stock'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='tech_stock_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('reward_per_unit__gte', 0)), name='tech_stock_reward_nonnegative')],
            },
        ),
    ]
