# Generated by Django 5.2.17 on 2026-09-05 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productchangeevent_action_kind_and_more'),
        ('consignment', '0001_initial'),
        ('partners', '0001_initial'),
        ('warehouse', '0003_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('transfer', 'Передача на реализацию'), ('return', 'Возврат с реализации')], editable=False, max_length=16, verbose_name='Операция')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('quantity', models.PositiveIntegerField(editable=False, verbose_name='Количество')),
                ('reward_per_unit', models.DecimalField(decimal_places=2, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вознаграждение за единицу')),
                ('warehouse_quantity_before', models.PositiveIntegerField(editable=False, verbose_name='Остаток склада до')),
                ('warehouse_quantity_after', models.PositiveIntegerField(editable=False, verbose_name='Остаток склада после')),
                ('consignment_quantity_before', models.PositiveIntegerField(editable=False, verbose_name='На реализации до')),
                ('consignment_quantity_after', models.PositiveIntegerField(editable=False, verbose_name='На реализации после')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('cd', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_movements', to='catalog.cd', verbose_name='CD')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_movements', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
                ('platform', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_movements', to='partners.salesplatform', verbose_name='Площадка')),
                ('tech', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_movements', to='catalog.tech', verbose_name='Техника')),
                ('warehouse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_movements', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'операция реализации',
                'verbose_name_plural': 'операции реализации',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='consignment_movement_quantity_positive'), models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='consignment_movement_exact_product')],
            },
        ),
    ]
