# Generated by Django 5.2.17 on 2026-09-05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def move_existing_data(apps, schema_editor):
    Movement = apps.get_model("consignment", "ConsignmentMovement")
    MovementItem = apps.get_model("consignment", "ConsignmentMovementItem")
    CDStock = apps.get_model("consignment", "CDConsignmentStock")
    TechStock = apps.get_model("consignment", "TechConsignmentStock")
    Warehouse = apps.get_model("warehouse", "Warehouse")

    fallback_warehouse = Warehouse.objects.order_by("pk").first()
    for movement in Movement.objects.select_related("cd", "tech").order_by("pk"):
        product = movement.cd if movement.product_kind == "cd" else movement.tech
        MovementItem.objects.create(
            movement_id=movement.pk,
            product_kind=movement.product_kind,
            cd_id=movement.cd_id,
            tech_id=movement.tech_id,
            product_name_snapshot=product.name,
            product_sku_snapshot=product.sku,
            quantity=movement.quantity,
            receivable_per_unit=movement.reward_per_unit,
            warehouse_quantity_before=movement.warehouse_quantity_before,
            warehouse_quantity_after=movement.warehouse_quantity_after,
            consignment_quantity_before=movement.consignment_quantity_before,
            consignment_quantity_after=movement.consignment_quantity_after,
        )

    for stock_model, product_kind, product_field in (
        (CDStock, "cd", "cd"),
        (TechStock, "tech", "tech"),
    ):
        for stock in stock_model.objects.all():
            movement = Movement.objects.filter(
                platform_id=stock.platform_id,
                product_kind=product_kind,
                **{f"{product_field}_id": getattr(stock, f"{product_field}_id")},
            ).order_by("-created_at", "-pk").first()
            warehouse_id = movement.warehouse_id if movement else (
                fallback_warehouse.pk if fallback_warehouse else None
            )
            if warehouse_id is None:
                raise RuntimeError(
                    "Невозможно определить склад-источник старого остатка на реализации."
                )
            stock.warehouse_id = warehouse_id
            stock.save(update_fields=("warehouse",))


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_cd_barcode_alter_tech_barcode"),
        ("consignment", "0002_consignmentmovement"),
        ("partners", "0001_initial"),
        ("warehouse", "0003_transfers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsignmentMovementItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_kind", models.CharField(choices=[("cd", "CD"), ("tech", "Tech")], editable=False, max_length=8, verbose_name="Тип товара")),
                ("product_name_snapshot", models.CharField(editable=False, max_length=255, verbose_name="Название товара")),
                ("product_sku_snapshot", models.CharField(editable=False, max_length=100, verbose_name="Артикул")),
                ("quantity", models.PositiveIntegerField(editable=False, verbose_name="Количество")),
                ("receivable_per_unit", models.DecimalField(decimal_places=2, editable=False, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Сумма к получению за единицу")),
                ("warehouse_quantity_before", models.PositiveIntegerField(editable=False, verbose_name="Остаток склада до")),
                ("warehouse_quantity_after", models.PositiveIntegerField(editable=False, verbose_name="Остаток склада после")),
                ("consignment_quantity_before", models.PositiveIntegerField(editable=False, verbose_name="На реализации до")),
                ("consignment_quantity_after", models.PositiveIntegerField(editable=False, verbose_name="На реализации после")),
            ],
            options={
                "verbose_name": "позиция операции реализации",
                "verbose_name_plural": "позиции операций реализации",
                "ordering": ("id",),
            },
        ),
        migrations.RemoveConstraint(model_name="cdconsignmentstock", name="unique_cd_platform_stock"),
        migrations.RemoveConstraint(model_name="cdconsignmentstock", name="cd_stock_reward_nonnegative"),
        migrations.RemoveConstraint(model_name="consignmentmovement", name="consignment_movement_quantity_positive"),
        migrations.RemoveConstraint(model_name="consignmentmovement", name="consignment_movement_exact_product"),
        migrations.RemoveConstraint(model_name="techconsignmentstock", name="unique_tech_platform_stock"),
        migrations.RemoveConstraint(model_name="techconsignmentstock", name="tech_stock_reward_nonnegative"),
        migrations.RenameField(model_name="cdconsignmentstock", old_name="reward_per_unit", new_name="receivable_per_unit"),
        migrations.RenameField(model_name="techconsignmentstock", old_name="reward_per_unit", new_name="receivable_per_unit"),
        migrations.AlterField(
            model_name="cdconsignmentstock", name="receivable_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Сумма к получению за единицу"),
        ),
        migrations.AlterField(
            model_name="techconsignmentstock", name="receivable_per_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Сумма к получению за единицу"),
        ),
        migrations.AddField(
            model_name="cdconsignmentstock", name="warehouse",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="warehouse.warehouse", verbose_name="Склад-источник"),
        ),
        migrations.AddField(
            model_name="techconsignmentstock", name="warehouse",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="warehouse.warehouse", verbose_name="Склад-источник"),
        ),
        migrations.AddField(
            model_name="consignmentmovementitem", name="cd",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="consignment_movement_items", to="catalog.cd", verbose_name="CD"),
        ),
        migrations.AddField(
            model_name="consignmentmovementitem", name="movement",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="consignment.consignmentmovement", verbose_name="Операция"),
        ),
        migrations.AddField(
            model_name="consignmentmovementitem", name="tech",
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="consignment_movement_items", to="catalog.tech", verbose_name="Техника"),
        ),
        migrations.RunPython(move_existing_data, migrations.RunPython.noop),
        migrations.RemoveField(model_name="consignmentmovement", name="cd"),
        migrations.RemoveField(model_name="consignmentmovement", name="consignment_quantity_after"),
        migrations.RemoveField(model_name="consignmentmovement", name="consignment_quantity_before"),
        migrations.RemoveField(model_name="consignmentmovement", name="product_kind"),
        migrations.RemoveField(model_name="consignmentmovement", name="quantity"),
        migrations.RemoveField(model_name="consignmentmovement", name="reward_per_unit"),
        migrations.RemoveField(model_name="consignmentmovement", name="tech"),
        migrations.RemoveField(model_name="consignmentmovement", name="warehouse_quantity_after"),
        migrations.RemoveField(model_name="consignmentmovement", name="warehouse_quantity_before"),
        migrations.AlterField(
            model_name="cdconsignmentstock", name="warehouse",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.warehouse", verbose_name="Склад-источник"),
        ),
        migrations.AlterField(
            model_name="techconsignmentstock", name="warehouse",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.warehouse", verbose_name="Склад-источник"),
        ),
        migrations.AddConstraint(
            model_name="cdconsignmentstock",
            constraint=models.UniqueConstraint(fields=("platform", "warehouse", "cd"), name="unique_cd_platform_warehouse_stock"),
        ),
        migrations.AddConstraint(
            model_name="cdconsignmentstock",
            constraint=models.CheckConstraint(condition=models.Q(("receivable_per_unit__gte", 0)), name="cd_stock_receivable_nonnegative"),
        ),
        migrations.AddConstraint(
            model_name="techconsignmentstock",
            constraint=models.UniqueConstraint(fields=("platform", "warehouse", "tech"), name="unique_tech_platform_warehouse_stock"),
        ),
        migrations.AddConstraint(
            model_name="techconsignmentstock",
            constraint=models.CheckConstraint(condition=models.Q(("receivable_per_unit__gte", 0)), name="tech_stock_receivable_nonnegative"),
        ),
        migrations.AddConstraint(
            model_name="consignmentmovementitem",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="consignment_movement_item_quantity_positive"),
        ),
        migrations.AddConstraint(
            model_name="consignmentmovementitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cd__isnull", False), ("product_kind", "cd"), ("tech__isnull", True)),
                    models.Q(("cd__isnull", True), ("product_kind", "tech"), ("tech__isnull", False)),
                    _connector="OR",
                ),
                name="consignment_movement_item_exact_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="consignmentmovementitem",
            constraint=models.UniqueConstraint(condition=models.Q(("cd__isnull", False)), fields=("movement", "cd"), name="unique_consignment_movement_cd"),
        ),
        migrations.AddConstraint(
            model_name="consignmentmovementitem",
            constraint=models.UniqueConstraint(condition=models.Q(("tech__isnull", False)), fields=("movement", "tech"), name="unique_consignment_movement_tech"),
        ),
    ]
