# Generated by Django 5.2.17 on 2026-09-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0003_consignment_multiline_and_sales_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdconsignmentstock',
            options={'permissions': [('transfer_stock', 'Может передавать товар на реализацию'), ('return_stock', 'Может возвращать товар с реализации'), ('change_consignment_reward', 'Может изменять вознаграждение на реализации')], 'verbose_name': 'остаток CD на реализации', 'verbose_name_plural': 'остатки CD на реализации'},
        ),
    ]
