# Generated by Django 5.2.17 on 2026-09-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0003_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProcurementOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название товара')),
                ('article_snapshot', models.CharField(editable=False, max_length=100, verbose_name='Артикул')),
                ('supplier_price_aed_snapshot', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Цена поставщика, AED')),
                ('prepayment_unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Цена предоплаты')),
                ('postpayment_unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Цена постоплаты')),
                ('prepayment_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество по предоплате')),
                ('postpayment_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество по постоплате')),
            ],
            options={
                'verbose_name': 'позиция клиентского закупочного заказа',
                'verbose_name_plural': 'позиции клиентского закупочного заказа',
                'ordering': ('product_name_snapshot', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Сумма возврата')),
            ],
            options={
                'verbose_name': 'корректировка закупочного заказа',
                'verbose_name_plural': 'корректировки закупочных заказов',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderAdjustmentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], max_length=8, verbose_name='Тип товара')),
                ('product_id_snapshot', models.PositiveBigIntegerField(verbose_name='ID товара')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('field_name', models.CharField(max_length=40, verbose_name='Поле')),
                ('old_value', models.PositiveIntegerField(verbose_name='Было')),
                ('new_value', models.PositiveIntegerField(verbose_name='Стало')),
            ],
            options={
                'verbose_name': 'изменение в корректировке заказа',
                'verbose_name_plural': 'изменения в корректировке заказа',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'подборка заказов поставщикам',
                'verbose_name_plural': 'подборки заказов поставщикам',
                'ordering': ('-created_at', '-id'),
                'permissions': [('generate_supplier_orders', 'Заказы: формирование заказов поставщикам')],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], editable=False, max_length=8, verbose_name='Тип товара')),
                ('product_name_snapshot', models.CharField(editable=False, max_length=255, verbose_name='Название товара')),
                ('article_snapshot', models.CharField(editable=False, max_length=100, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('supplier_price_aed_snapshot', models.DecimalField(decimal_places=6, editable=False, max_digits=20, verbose_name='Цена поставщика, AED')),
            ],
            options={
                'verbose_name': 'строка заказа поставщику',
                'verbose_name_plural': 'строки заказов поставщикам',
                'ordering': ('supplier__name', 'product_name_snapshot', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтверждён'), ('receiving', 'Принимается'), ('completed', 'Выполнен')], max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтверждён'), ('receiving', 'Принимается'), ('completed', 'Выполнен')], max_length=20, verbose_name='Новый статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'смена статуса закупочного заказа',
                'verbose_name_plural': 'смены статусов закупочных заказов',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255, verbose_name='Получатель')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтверждён'), ('receiving', 'Принимается'), ('completed', 'Выполнен')], default='created', editable=False, max_length=20, verbose_name='Статус')),
                ('prepayment_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Предоплата')),
                ('postpayment_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Постоплата')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Итого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_procurement_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('payment_warehouse', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_procurement_orders', to='warehouse.warehouse', verbose_name='Склад оплаты')),
            ],
            options={
                'verbose_name': 'клиентский закупочный заказ',
                'verbose_name_plural': 'клиентские закупочные заказы',
                'ordering': ('-created_at', '-id'),
                'permissions': [('view_orders', 'Заказы: просмотр списка'), ('view_order_detail', 'Заказы: просмотр заказа'), ('create_order', 'Заказы: создание'), ('edit_created_order', 'Заказы: изменение созданного заказа'), ('confirm_order', 'Заказы: подтверждение и предоплата'), ('start_receiving', 'Заказы: начало приёмки'), ('edit_receiving_order', 'Заказы: корректировка при приёмке'), ('complete_order', 'Заказы: выполнение и постоплата'), ('view_order_adjustments', 'Заказы: просмотр корректировок')],
            },
        ),
    ]
