# Generated by Django 5.2.17 on 2026-09-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_alter_cd_barcode_alter_tech_barcode'),
        ('orders', '0001_initial'),
        ('partners', '0001_initial'),
        ('price', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprocurementorder',
            name='price_list',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='price.procurementpricelist', verbose_name='Исходный закупочный прайс'),
        ),
        migrations.AddField(
            model_name='customerorderstatusevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='orders.customerprocurementorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='customerprocurementorderitem',
            name='cd',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cd'),
        ),
        migrations.AddField(
            model_name='customerprocurementorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.customerprocurementorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='customerprocurementorderitem',
            name='price_list_item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='price.procurementpricelistitem', verbose_name='Позиция исходного прайса'),
        ),
        migrations.AddField(
            model_name='customerprocurementorderitem',
            name='selected_supplier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_items', to='partners.supplier', verbose_name='Выбранный поставщик'),
        ),
        migrations.AddField(
            model_name='customerprocurementorderitem',
            name='tech',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.tech'),
        ),
        migrations.AddField(
            model_name='orderadjustment',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='orderadjustment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='orders.customerprocurementorder', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderadjustmentchange',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='orders.orderadjustment', verbose_name='Корректировка'),
        ),
        migrations.AddField(
            model_name='supplierorderbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='supplierorderbatch',
            name='source_orders',
            field=models.ManyToManyField(related_name='supplier_order_batches', to='orders.customerprocurementorder', verbose_name='Исходные заказы'),
        ),
        migrations.AddField(
            model_name='supplierorderbatchline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.supplierorderbatch', verbose_name='Подборка'),
        ),
        migrations.AddField(
            model_name='supplierorderbatchline',
            name='cd',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.cd'),
        ),
        migrations.AddField(
            model_name='supplierorderbatchline',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_batch_lines', to='partners.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='supplierorderbatchline',
            name='tech',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.tech'),
        ),
        migrations.AddConstraint(
            model_name='customerprocurementorder',
            constraint=models.CheckConstraint(condition=models.Q(('prepayment_total__gte', 0)), name='order_prepayment_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerprocurementorder',
            constraint=models.CheckConstraint(condition=models.Q(('postpayment_total__gte', 0)), name='order_postpayment_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerprocurementorder',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='order_grand_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerprocurementorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='customer_order_item_exact_product'),
        ),
        migrations.AddConstraint(
            model_name='customerprocurementorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'price_list_item'), name='unique_order_price_list_item'),
        ),
        migrations.AddConstraint(
            model_name='customerprocurementorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('prepayment_quantity__gt', 0), ('postpayment_quantity__gt', 0), _connector='OR'), name='customer_order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderbatchline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='supplier_batch_line_exact_product'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderbatchline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supplier_batch_quantity_positive'),
        ),
    ]
