# Generated by Django 5.2.17 on 2026-09-12 16:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0009_remove_cashtransaction_cash_transaction_safe_matches_type_and_more'),
        ('warehouse', '0004_alter_warehouse_options_warehousestoragelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущая задолженность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'кредитор',
                'verbose_name_plural': 'кредиторы',
                'ordering': ('name', 'id'),
                'permissions': [('view_creditors', 'Может просматривать кредиторов'), ('change_debt', 'Может изменять задолженность кредиторов'), ('view_history', 'Может просматривать историю кредиторов')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_debt__gte', 0)), name='creditor_debt_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='CreditorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_debt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Задолженность до')),
                ('new_debt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Задолженность после')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Изменение задолженности')),
                ('money_source_type', models.CharField(choices=[('cash', 'Касса'), ('safe', 'Сейф')], max_length=8, verbose_name='Денежное хранилище')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Проведена')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Провёл')),
                ('cash_transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_transaction', to='cash.cashtransaction', verbose_name='Запись денежного журнала')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='creditors.creditor', verbose_name='Кредитор')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_transactions', to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'операция кредитора',
                'verbose_name_plural': 'операции кредиторов',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('old_debt__gte', 0)), name='creditor_tx_old_debt_nonnegative'), models.CheckConstraint(condition=models.Q(('new_debt__gte', 0)), name='creditor_tx_new_debt_nonnegative'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='creditor_tx_amount_positive'), models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='creditor_tx_delta_nonzero')],
            },
        ),
    ]
