# Generated by Django 5.2.17 on 2026-09-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='consignment_platform',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='partners.salesplatform', verbose_name='Площадка реализации'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_type',
            field=models.CharField(choices=[('retail', 'Розничная'), ('wholesale', 'Оптовая'), ('yandex_market', 'Яндекс Маркет'), ('consignment', 'Реализация')], max_length=24, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Розница'), ('wholesale_pickup', 'Опт самовывоз'), ('wholesale_delivery', 'Опт доставка'), ('avito', 'Авито'), ('yandex_market', 'Яндексмаркет'), ('consignment', 'Реализация')], max_length=24, verbose_name='Тип продажи'),
        ),
    ]
