# Generated by Django 5.2.17 on 2026-09-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_consignment_platform_alter_sale_price_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('view_sales', 'Может просматривать незавершённые продажи'), ('view_completed_sales', 'Может просматривать завершённые продажи'), ('view_sale_detail', 'Может просматривать подробности продажи'), ('create_sale', 'Может создавать продажи'), ('edit_unpaid_postpay_sale', 'Может изменять неоплаченную продажу с постоплатой'), ('advance_order_status', 'Может менять статус заказа'), ('mark_sale_paid', 'Может подтверждать оплату продажи'), ('import_wholesale_price', 'Может импортировать оптовый XLSX в новую продажу')], 'verbose_name': 'продажа', 'verbose_name_plural': 'продажи'},
        ),
    ]
