# Generated by Django 5.2.17 on 2026-09-10 07:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('sales', '0003_alter_sale_options'),
        ('warehouse', '0003_transfers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('view_sales', 'Может просматривать незавершённые продажи'), ('view_completed_sales', 'Может просматривать завершённые продажи'), ('view_sale_detail', 'Может просматривать подробности продажи'), ('create_sale', 'Может создавать продажи'), ('edit_unpaid_postpay_sale', 'Может изменять неоплаченную продажу с постоплатой'), ('advance_order_status', 'Может менять статус заказа'), ('mark_sale_paid', 'Может подтверждать оплату продажи'), ('import_wholesale_price', 'Может импортировать оптовый XLSX в новую продажу'), ('cancel_sale', 'Может отменять продажи')], 'verbose_name': 'продажа', 'verbose_name_plural': 'продажи'},
        ),
        migrations.AddField(
            model_name='sale',
            name='cancellation_comment',
            field=models.TextField(blank=True, editable=False, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Отменена'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возвращённая сумма'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='sale_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('total_amount'))), name='sale_refund_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_comment', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('refunded_amount', 0)), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancellation_comment', ''), _negated=True)), _connector='OR'), name='sale_cancellation_fields_consistent'),
        ),
    ]
