# Generated by Django 5.2.17 on 2026-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_options_sale_cancellation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price_type',
            field=models.CharField(choices=[('retail', 'Цена Avito'), ('wholesale', 'Оптовая'), ('yandex_market', 'Яндекс Маркет'), ('consignment', 'Реализация')], max_length=24, verbose_name='Тип цены'),
        ),
    ]
