# Generated by Django 5.2.17 on 2026-09-12 16:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def backfill_cash_received(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    CashTransaction = apps.get_model("cash", "CashTransaction")
    paid_sales = Sale.objects.filter(
        payment_method__in=("cash", "cash_postpay"), payment_status="paid",
    )
    for sale in paid_sales.iterator():
        payment = CashTransaction.objects.filter(
            sale_id=sale.pk, operation_type="sale_payment",
        ).order_by("id").first()
        received = payment.amount if payment else sale.total_amount
        sale.cash_received_amount = received
        sale.extra_cash_amount = max(received - sale.total_amount, 0)
        sale.save(update_fields=("cash_received_amount", "extra_cash_amount"))


def clear_cash_received(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    Sale.objects.update(cash_received_amount=None, extra_cash_amount=0)


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_remove_cashtransaction_cash_transaction_safe_matches_type_and_more'),
        ('partners', '0002_supplier_priority'),
        ('sales', '0005_alter_sale_price_type'),
        ('warehouse', '0004_alter_warehouse_options_warehousestoragelocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='sale_refund_not_above_total',
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Получено от покупателя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='extra_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма сверх стоимости'),
        ),
        migrations.AddField(
            model_name='sale',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.RunPython(backfill_cash_received, clear_cash_received),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_received_amount__isnull', True), ('refunded_amount__lte', models.F('total_amount'))), models.Q(('cash_received_amount__isnull', False), ('refunded_amount__lte', models.F('cash_received_amount'))), _connector='OR'), name='sale_refund_not_above_received'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('cash_received_amount__isnull', True), ('cash_received_amount__gte', models.F('total_amount')), _connector='OR'), name='sale_cash_received_not_below_total'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('extra_cash_amount__gte', 0)), name='sale_extra_cash_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ('cash', 'cash_postpay')), models.Q(('cash_received_amount__isnull', True), ('extra_cash_amount', 0)), _connector='OR'), name='sale_bank_has_no_cash_received'),
        ),
    ]
