# Generated by Django 5.2.17 on 2026-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_sale_sale_refund_not_above_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('view_sales', 'Может просматривать незавершённые продажи'), ('view_completed_sales', 'Может просматривать завершённые продажи'), ('view_sale_detail', 'Может просматривать подробности продажи'), ('create_sale', 'Может создавать продажи'), ('edit_unpaid_postpay_sale', 'Может изменять неоплаченную продажу с постоплатой'), ('advance_order_status', 'Может менять статус заказа'), ('mark_sale_paid', 'Может подтверждать оплату продажи'), ('import_wholesale_price', 'Может импортировать оптовый XLSX в новую продажу'), ('cancel_sale', 'Может отменять продажи'), ('view_sales_statistics', 'Может просматривать статистику продаж и прибыль'), ('export_sales_statistics', 'Может экспортировать статистику продаж')], 'verbose_name': 'продажа', 'verbose_name_plural': 'продажи'},
        ),
        migrations.AddField(
            model_name='salecditem',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='Себестоимость единицы на момент продажи'),
        ),
        migrations.AddField(
            model_name='saletechitem',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='Себестоимость единицы на момент продажи'),
        ),
    ]
