# Generated by Django 5.2.17 on 2026-09-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_options_salecditem_unit_cost_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCustomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена единицы')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма строки')),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True, verbose_name='Себестоимость единицы на момент продажи')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article_snapshot', models.CharField(max_length=100, verbose_name='Артикул')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_items', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'произвольная позиция продажи',
                'verbose_name_plural': 'произвольные позиции продаж',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_custom_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_custom_price_nonnegative'), models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='sale_custom_total_nonnegative'), models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='sale_custom_cost_nonnegative')],
            },
        ),
    ]
