# Generated by Django 5.2.17 on 2026-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salecustomitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salecustomitem',
            constraint=models.CheckConstraint(condition=models.Q(('product_name_snapshot', ''), _negated=True), name='sale_custom_name_nonempty'),
        ),
    ]
