# Generated by Django 5.2.17 on 2026-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salecustomitem_sale_custom_name_nonempty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salecustomitem',
            name='sale_custom_cost_nonnegative',
        ),
        migrations.AddConstraint(
            model_name='salecustomitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0), ('unit_cost_snapshot__isnull', False)), name='sale_custom_cost_nonnegative'),
        ),
    ]
