# Generated by Django 5.2.17 on 2026-09-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_salecustomitem_sale_custom_cost_nonnegative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecustomitem',
            name='article_snapshot',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Артикул'),
        ),
    ]
