# Generated by Django 5.2.17 on 2026-09-28 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_cd_zero_stock_since_tech_zero_stock_since'),
        ('partners', '0002_supplier_priority'),
        ('sales', '0011_alter_salecustomitem_article_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_kind', models.CharField(choices=[('cd', 'CD'), ('tech', 'Tech')], max_length=8, verbose_name='Тип товара')),
                ('source_stock_id', models.PositiveBigIntegerField(verbose_name='ID партии реализации')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Вознаграждение за единицу')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма строки')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Себестоимость единицы на момент продажи')),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article_snapshot', models.CharField(max_length=100, verbose_name='Артикул')),
                ('platform_name_snapshot', models.CharField(max_length=255, verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'позиция реализации в продаже',
                'verbose_name_plural': 'позиции реализации в продажах',
            },
        ),
        migrations.AddField(
            model_name='salecditem',
            name='unit_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка на единицу'),
        ),
        migrations.AddField(
            model_name='salecustomitem',
            name='unit_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка на единицу'),
        ),
        migrations.AddField(
            model_name='saletechitem',
            name='unit_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка на единицу'),
        ),
        migrations.AddConstraint(
            model_name='salecditem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_discount__gte', 0), ('unit_discount__lte', models.F('unit_price'))), name='sale_cd_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='salecustomitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_discount__gte', 0), ('unit_discount__lte', models.F('unit_price'))), name='sale_custom_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='saletechitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_discount__gte', 0), ('unit_discount__lte', models.F('unit_price'))), name='sale_tech_discount_valid'),
        ),
        migrations.AddField(
            model_name='saleconsignmentitem',
            name='cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_sale_items', to='catalog.cd'),
        ),
        migrations.AddField(
            model_name='saleconsignmentitem',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='partners.salesplatform', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='saleconsignmentitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_items', to='sales.sale', verbose_name='Продажа'),
        ),
        migrations.AddField(
            model_name='saleconsignmentitem',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_sale_items', to='catalog.tech'),
        ),
        migrations.AddConstraint(
            model_name='saleconsignmentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cd__isnull', False), ('product_kind', 'cd'), ('tech__isnull', True)), models.Q(('cd__isnull', True), ('product_kind', 'tech'), ('tech__isnull', False)), _connector='OR'), name='sale_consignment_exact_product'),
        ),
        migrations.AddConstraint(
            model_name='saleconsignmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_consignment_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleconsignmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_consignment_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleconsignmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='sale_consignment_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleconsignmentitem',
            constraint=models.UniqueConstraint(fields=('sale', 'product_kind', 'source_stock_id'), name='unique_sale_consignment_stock'),
        ),
    ]
