# Generated by Django 5.2.17 on 2026-09-29 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_cd_zero_stock_since_tech_zero_stock_since'),
        ('sales', '0012_saleconsignmentitem_salecditem_unit_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecditem',
            name='avito_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комиссия Avito'),
        ),
        migrations.AddField(
            model_name='salecditem',
            name='avito_commission_enabled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Учитывать комиссию Avito 0,5%'),
        ),
        migrations.AddField(
            model_name='salecustomitem',
            name='avito_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комиссия Avito'),
        ),
        migrations.AddField(
            model_name='salecustomitem',
            name='avito_commission_enabled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Учитывать комиссию Avito 0,5%'),
        ),
        migrations.AddField(
            model_name='saletechitem',
            name='avito_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комиссия Avito'),
        ),
        migrations.AddField(
            model_name='saletechitem',
            name='avito_commission_enabled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Учитывать комиссию Avito 0,5%'),
        ),
        migrations.AddConstraint(
            model_name='salecditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('avito_commission_amount', 0), ('avito_commission_enabled', False)), models.Q(('avito_commission_amount__gte', 1), ('avito_commission_enabled', True)), _connector='OR'), name='sale_cd_avito_commission_consistent'),
        ),
        migrations.AddConstraint(
            model_name='salecustomitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('avito_commission_amount', 0), ('avito_commission_enabled', False)), models.Q(('avito_commission_amount__gte', 1), ('avito_commission_enabled', True)), _connector='OR'), name='sale_custom_avito_commission_consistent'),
        ),
        migrations.AddConstraint(
            model_name='saletechitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('avito_commission_amount', 0), ('avito_commission_enabled', False)), models.Q(('avito_commission_amount__gte', 1), ('avito_commission_enabled', True)), _connector='OR'), name='sale_tech_avito_commission_consistent'),
        ),
    ]
