# Generated by Django 5.2.17 on 2026-10-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_storefront', '0001_initial'),
        ('sales', '0014_merge_wholesale_sale_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_address_snapshot',
            field=models.TextField(blank=True, verbose_name='Адрес на момент заказа'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий покупателя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_extra_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Дополнительный телефон покупателя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_name_snapshot',
            field=models.CharField(blank=True, max_length=160, verbose_name='Контактное имя на момент заказа'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_phone_snapshot',
            field=models.CharField(blank=True, max_length=40, verbose_name='Основной телефон на момент заказа'),
        ),
        migrations.AddField(
            model_name='sale',
            name='storefront_source',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='sale',
            name='wholesale_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='resource_storefront.wholesalecontact', verbose_name='Оптовый контакт'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
    ]
