# Generated by Django 5.2.17 on 2026-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_sale_buyer_address_snapshot_sale_buyer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_contact_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='Способы связи покупателя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_telegram',
            field=models.CharField(blank=True, max_length=80, verbose_name='Telegram покупателя'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_whatsapp',
            field=models.CharField(blank=True, max_length=40, verbose_name='WhatsApp покупателя'),
        ),
    ]
