# Generated by Django 5.2.17 on 2026-10-03 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_supplier_priority'),
        ('resource_storefront', '0005_initialize_retail_warehouse'),
        ('sales', '0016_sale_buyer_contact_methods_sale_buyer_telegram_and_more'),
        ('warehouse', '0005_transfer_cost_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('undefined', 'Не определён'), ('cash', 'Наличные'), ('cash_postpay', 'Наличные — постоплата'), ('bank_account', 'Банковский счёт')], max_length=24, verbose_name='Способ оплаты'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method', 'undefined'), _negated=True), ('payment_status', 'unpaid'), _connector='OR'), name='sale_undefined_payment_unpaid'),
        ),
    ]
